// Package fakeprovider is a deterministic HTTP Range endpoint with an access resolver, counters and fault
// injection. It is the only "provider" the automated gates ever contact.
//
// IT IS DETERMINISTIC ON PURPOSE. Object bytes are a pure function of the object reference and the offset, so
// a test can assert the exact bytes a read returned without shipping fixtures, and two runs of the same gate
// compare the same numbers. Every counter here is what the amplification budget is measured against.
package fakeprovider

import (
	"crypto/sha256"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

// Fault is an injected misbehaviour, applied to one object.
type Fault string

const (
	FaultNone Fault = ""
	// FaultFullBodyOnRange answers a ranged request with 200 and the whole object. Accepting one is the most
	// expensive protocol failure available here.
	FaultFullBodyOnRange Fault = "full-body-on-range"
	FaultMalformedRange  Fault = "malformed-content-range"
	FaultMismatchedRange Fault = "mismatched-content-range"
	FaultShortBody       Fault = "short-body"
	FaultWrongTotalSize  Fault = "wrong-total-size"
	FaultLongBody        Fault = "long-body"
	Fault401             Fault = "status-401"
	Fault403             Fault = "status-403"
	Fault410             Fault = "status-410"
	Fault429             Fault = "status-429"
	Fault503             Fault = "status-503"
	FaultTimeout         Fault = "timeout"
	FaultRedirect        Fault = "redirect"
	FaultDisallowedHost  Fault = "disallowed-host"
	FaultResolverError   Fault = "resolver-error"
	// FaultDelayedClose serves the CORRECT bytes for the granted range, chunked, and then delays its terminal
	// chunk. A client that insists on reading to EOF before accepting the range stalls here for the whole
	// request timeout even though the server did nothing wrong.
	FaultDelayedClose Fault = "delayed-close"
)

// Object is one served byte stream.
//
// Path, when non-empty, makes the object FILE BACKED: the bytes come from that file rather than from the
// deterministic content function. The synthetic function is what every amplification and protocol gate wants,
// because it lets a test assert exact bytes without shipping a fixture. It is useless to a gate that needs a
// reader which DECODES what it fetched — a media server probes a container header, and pseudo-random bytes do
// not have one. So a file-backed object exists for exactly that case, and the file it names is generated by
// the gate that uses it, on the machine that runs it, from a synthetic signal.
type Object struct {
	Ref  string
	Size int64
	Path string
}

// Counters are read by the gates. Every one of them is a number a budget is asserted against.
type Counters struct {
	Resolutions atomic.Int64
	// RangeRequests counts ARRIVALS: incremented when a request reaches the handler, before its outcome is
	// known. It is the right denominator for a request ceiling and the wrong one for a partition identity;
	// AccountedResponses is the partition's side. See the accounting lock.
	RangeRequests atomic.Int64
	// AccountedResponses counts requests whose outcome has been RECORDED — a body classified, or no body
	// served — and it advances in the same critical section as that recording. The identity is
	//
	//	Chunk + Small + Partial + Oversized + Bodyless == AccountedResponses
	//
	// which holds with any number of requests still in flight, because both sides move together.
	//
	// IT IS NOT NAMED "COMPLETED", AND THE DISTINCTION IS THE ONE THIS FILE KEEPS HAVING TO LEARN. The
	// increment happens BEFORE the body is written to the socket — deliberately, so bytes cannot reach a
	// client before the counters describing them — so at the moment it moves the HTTP response is not
	// complete and may still fail on a broken pipe. Calling it Completed would claim delivery this endpoint
	// does not observe. It counts accounting, which is exactly what it does and all it is used for.
	AccountedResponses atomic.Int64
	// HeldRequests is a LIFETIME count of requests that entered a hold. CurrentHeldWaiters is how many are
	// blocked right now, and HoldTimeouts counts holds that lapsed instead of being released.
	HeldRequests       atomic.Int64
	CurrentHeldWaiters atomic.Int64
	HoldTimeouts       atomic.Int64
	// BytesServed is the COMMITTED payload length: what the handler undertook to write, counted before it
	// wrote it. IT IS NOT A DELIVERY FIGURE, and the wire key keeps its historical spelling only because the
	// three single-server data-plane gates read it and their recorded runs describe exactly this quantity.
	// Everything that needs "what the handler's write calls returned" reads ObservedBytes instead.
	BytesServed atomic.Int64
	// ObservedBytes is the sum of the counts `http.ResponseWriter.Write` RETURNED, recorded after each call.
	//
	// WHAT THAT IS AND, MORE IMPORTANTLY, WHAT IT IS NOT. It is the number of bytes this handler successfully
	// handed to the HTTP stack. It is NOT proof of peer receipt, NOT a TCP acknowledgement, NOT the exact
	// count of bytes on the wire (chunked framing, TLS and headers are not in it) and NOT provider billing.
	// It is strictly an APPLICATION-WRITE observation, and every figure derived from it says so.
	ObservedBytes atomic.Int64
	// CompletedBodies wrote their whole committed payload with no error; TruncatedBodies did not. The two sum
	// to the count of bodied responses only once nothing is still writing — see BodiesInFlight.
	CompletedBodies atomic.Int64
	TruncatedBodies atomic.Int64
	// BodiesInFlight is a live GAUGE: how many bodies are between their commit and their observation right
	// now. It is the only field that answers "may an observed-byte figure be read from this snapshot at all".
	BodiesInFlight    atomic.Int64
	Served429         atomic.Int64
	FullBodyServed    atomic.Int64
	ExpiredRejected   atomic.Int64
	PeakConcurrent    atomic.Int64
	CurrentConcurrent atomic.Int64
	PeakConns         atomic.Int64
	CurrentConns      atomic.Int64

	// REQUEST SHAPE, IN FOUR SIZE BUCKETS AND NOTHING ELSE.
	//
	// WHY THIS EXISTS. A gate measured 32,505,856 bytes over 10 ranged requests for one object and could say
	// nothing about the mix: 7.75 demand blocks is not a whole number of anything, so the total is some
	// combination of full 4 MiB blocks and smaller probe or tail reads. A budget derived from a total that
	// cannot be decomposed is a budget derived from a coincidence, and the honest response is to measure the
	// shape rather than to pick a multiplier that clears the observation.
	//
	// WHY FOUR AND NOT THREE, WHICH IS WHAT A REAL GATE RUN TAUGHT. The middle bucket used to be one
	// undifferentiated "other", asserted at ZERO because eight instrumented diagnostic windows had never
	// produced one. Every one of those windows scanned a single large object COLD. gate7's corpus window —
	// the first ever instrumented scan of a mixed-size library that reads AROUND already-cached data —
	// produced thirteen of them, 35,415,553 bytes, and failed a budget that said they could not exist.
	//
	// They were not waste. `readpath.demandBlock` computes a block inside the GAP between cached probe
	// windows and clips it to the gap's end, so a read bounded by cached data legitimately returns something
	// between one probe window and one demand block. That is the daemon fetching LESS, not more.
	//
	// A body ABOVE a demand block is a different animal entirely — a coalesced read or a full-body answer to
	// a ranged request — and has never occurred. Folding both into one bucket meant a budget could not admit
	// the harmless case without also admitting the harmful one. So they are separated:
	//
	//	small     n <= one probe window
	//	chunk     n == one demand block, exactly
	//	partial   one probe window < n < one demand block   (a block clipped by a cache gap or by EOF)
	//	oversized n > one demand block                      (never legitimate)
	//
	// WHY FLAT BUCKETS AND NOT A LOG. Anything per-request is a record of what was read and when, and this
	// endpoint serves media on behalf of a product whose whole argument is about not leaking access
	// material. Cumulative counts and byte totals in fixed buckets answer "what mix of sizes was served"
	// without retaining a single URL, header, lease, offset or per-request ordering. There is nothing to redact
	// because there is nothing here to identify.
	ChunkResponses     atomic.Int64
	ChunkBytes         atomic.Int64
	SmallResponses     atomic.Int64
	SmallBytes         atomic.Int64
	PartialResponses   atomic.Int64
	PartialBytes       atomic.Int64
	OversizedResponses atomic.Int64
	OversizedBytes     atomic.Int64
	// BodylessResponses is every ranged request that returned WITHOUT a body: an unknown object, a missing
	// file, a malformed Range, and each of the injected refusals — 401, 403, 410, 429, 503, a timeout, a
	// redirect. It exists so the request partition is an equation rather than an approximation:
	//
	//	Chunk + Small + Partial + Oversized + Bodyless == AccountedResponses
	//
	// AGAINST ACCOUNTED RESPONSES, NOT ARRIVALS. This comment said RangeRequests until gate9 showed why it
	// could not: arrivals are counted when a request lands and its class when the body is served, so a
	// request in flight at a snapshot sits on one side of the equation only.
	//
	// IT IS COUNTED STRUCTURALLY, NOT ENUMERATED. `serveRange` defers an increment that fires unless a body
	// was classified, so a no-body branch added tomorrow is accounted for by nobody having to remember it.
	// The first draft of this reconciliation added back only Served429 and ExpiredRejected and was short by
	// a dozen paths, while its gate name claimed to cover every request.
	BodylessResponses atomic.Int64
}

// The bucket boundaries, and both are read off the daemon rather than chosen here.
const (
	// chunkResponseBytes is readpath.DefaultConfig().ChunkBytes: the daemon's demand block. A response of
	// exactly this size is one full block.
	chunkResponseBytes = 4 * 1024 * 1024
	// smallResponseBytes is manifest.ProbeWindowBytes: one scan window. At or under this, a response is a
	// probe-sized read rather than a demand block.
	smallResponseBytes = 1024 * 1024
)

// recordShape files one served response into exactly one bucket. It is called wherever bytes are counted, so
// the buckets always sum to BytesServed and a caller can check that they do.
//
// THE BOUNDARIES ARE CLOSED ON THE SMALL SIDE AND OPEN ON THE OTHER, and the order of these cases is what
// makes them a partition rather than an overlap. Exactly one probe window is SMALL; one byte more is
// PARTIAL. Exactly one demand block is CHUNK; one byte more is OVERSIZED. A zero-length body is SMALL, which
// is the only sensible home for it: it is not a block, and it is certainly not oversized.
// It RETURNS the class it chose, so the per-object mirror of these counters cannot pick a different one.
// Two switch statements over the same boundaries is how the aggregate and the per-object view drift apart.
func (c *Counters) recordShape(n int64) responseClass {
	switch {
	case n == chunkResponseBytes:
		c.ChunkResponses.Add(1)
		c.ChunkBytes.Add(n)
		return classChunk
	case n <= smallResponseBytes:
		c.SmallResponses.Add(1)
		c.SmallBytes.Add(n)
		return classSmall
	case n < chunkResponseBytes:
		// Strictly between a probe window and a demand block: a block clipped by a cache gap or by EOF.
		c.PartialResponses.Add(1)
		c.PartialBytes.Add(n)
		return classPartial
	default:
		// Larger than a demand block. Nothing legitimate produces this.
		c.OversizedResponses.Add(1)
		c.OversizedBytes.Add(n)
		return classOversized
	}
}

// responseClass names the bucket a served body fell into, so the per-object arrays mirror the aggregate.
type responseClass int

const (
	classChunk responseClass = iota
	classSmall
	classPartial
	classOversized
)

// Server is the fake endpoint.
type Server struct {
	listener net.Listener
	server   *http.Server
	counters Counters

	mu sync.Mutex
	// objects by reference
	objects map[string]Object
	// faults by reference; remaining>0 means "apply this many more times, then stop"
	faults        map[string]*faultState
	leaseTTL      time.Duration
	leasePrefix   string
	publicBaseURL string
	leaseSeq      atomic.Uint64
	leases        map[string]time.Time
	now           func() time.Time
	timeoutFor    time.Duration
	// requireAuth makes the resolver refuse a request with no bearer credential.
	requireAuth bool
	token       string
	// holds blocks range requests for one object until released. See Hold.
	holds   map[string]chan struct{}
	maxHold time.Duration

	// PER-OBJECT BYTE ATTRIBUTION, AND EXACTLY AS MUCH OF IT AS A BUDGET NEEDS.
	//
	// WHY IT EXISTS. Every byte budget here was an AGGREGATE over a window: object sizes shaped the
	// allowance one at a time, but the measurement was a single `BytesServed`, so nothing could tell "each
	// object cost its own share" from "one object cost everything". gate8 made that material — its corpus
	// window exceeded the byte ceiling by 0.098% and the counters could not say which of forty objects did
	// it, or whether it was one large runaway or thirty-eight small extra passes.
	//
	// WHAT IT DELIBERATELY IS NOT. Not a request log. No reference, URL, lease, offset, status code or
	// timestamp — a served-byte total per object and nothing else.
	//
	// AND THE ONE THING IT DOES CARRY, STATED PLAINLY BECAUSE AN EARLIER COMMENT DENIED IT: an ORDERING. The
	// array is indexed by the order the GATE registered its objects, so position i is a stable handle for
	// one object across the run. That is not the ordering the redaction rule is about — there is no record
	// of which request came when, or in what sequence bytes were asked for — but writing "no ordering" was
	// false, and a privacy claim that overstates itself is worth less than a narrower true one.
	//
	// It is bounded by the number of registered objects, which the gate chooses; it cannot grow with
	// traffic. A reader learns how many objects exist and how many bytes each was asked for, both of which
	// the gate already knew when it created them.
	// POINTERS, NOT VALUES, AND THE REASON IS A RACE RATHER THAN A STYLE. Registration appends, which
	// reallocates the backing array; a writer that had read the slice header without the lock would then be
	// adding to a discarded array. Holding pointers lets the counter be fetched under the lock and
	// incremented after releasing it, so a served body never blocks on another object's accounting.
	objectOrdinal map[string]int
	objectBytes   []*atomic.Int64
	// objectObserved mirrors objectBytes for the APPLICATION-WRITE observation. Same ordinals, same privacy
	// properties, separate number: one is what was promised, the other what Write returned.
	objectObserved []*atomic.Int64
	// ORDINAL-ALIGNED PER-OBJECT CLASS COUNTS, so per-object class arithmetic is OBSERVED, not inferred.
	//
	// gate9 failed one object at 4.487x and the only way to say which responses were its was to notice that
	// 35,415,553 + 3 x 1,048,576 happened to equal its byte total exactly. That worked once; it is not a
	// method. These four arrays answer the question directly, under the same bounding and the same narrow
	// privacy claim as objectBytes: one entry per registered object, no reference, URL, lease, offset,
	// status, timestamp or per-request sequence.
	objectChunk     []*atomic.Int64
	objectPartial   []*atomic.Int64
	objectSmall     []*atomic.Int64
	objectOversized []*atomic.Int64

	// THE COMPOUND ACCOUNTING LOCK, HELD FOR A FEW ATOMIC ADDS AND NOTHING ELSE.
	//
	// THE DEFECT THIS CLOSES. Every counter here is individually atomic, and an earlier comment argued that
	// made a lock unnecessary. gate9 falsified it: the request partition `classified + bodyless == arrivals`
	// failed 5 against 4 because arrivals are counted when a request lands and its class when the body is
	// served, so a request in flight at a snapshot is counted on one side only. Individually atomic counters
	// are not a coherent SET.
	//
	// So classification, bytes, per-object totals and AccountedResponses all move together under this, and
	// reads them under it. A window's identity is then exact however many requests are in flight.
	//
	// IT IS NOT HELD ACROSS A HOLD, A READ OR A WRITE. `waitForHold` blocks before classification and this
	// lock is taken after it, so a deliberately held request cannot make /counters hang behind it — which
	// would turn the hold primitive into a way to freeze the instrument that measures it.
	accounting sync.Mutex
}

// Hold makes every subsequent ranged request for one object BLOCK until Release, or until maxHold elapses.
//
// WHY A GATE NEEDS THIS. Proving that something happened "while a library scan was running" against a real
// media server is otherwise a race: a four-entry scan takes a couple of seconds, and the handshake that
// observes it, publishes, and re-checks costs about as long. Retrying until the timing works is not evidence,
// it is a coin flip with a loop around it.
//
// Holding a provider read turns the timing into a fact. A scanner probing an entry whose bytes are not yet
// cached blocks in the read, so the scan is DETERMINISTICALLY still running for as long as the gate keeps the
// hold — long enough to observe it running, publish into it, and observe it running again afterwards. The
// hold is then released and the scan completes normally.
//
// THE BOUND IS NOT OPTIONAL. A gate that crashed between Hold and Release would otherwise wedge the daemon's
// read until its own request timeout, and every later assertion would fail for an unrelated reason. maxHold
// is deliberately shorter than the daemon's default request timeout so a forgotten release degrades into a
// slow read rather than a failed one.
func (s *Server) Hold(ref string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, exists := s.holds[ref]; !exists {
		s.holds[ref] = make(chan struct{})
	}
}

// Release lets any held request for one object proceed. Releasing something not held is not an error.
func (s *Server) Release(ref string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if ch, exists := s.holds[ref]; exists {
		close(ch)
		delete(s.holds, ref)
	}
}

// waitForHold blocks a request while its object is held, and counts the fact that it blocked.
func (s *Server) waitForHold(ref string) {
	s.mu.Lock()
	ch, held := s.holds[ref]
	s.mu.Unlock()
	if !held {
		return
	}
	// THREE NUMBERS, BECAUSE ONE OF THEM ANSWERS A QUESTION THE OTHERS CANNOT.
	//
	// HeldRequests is a lifetime counter: it says a request entered a hold AT SOME POINT. That is not what a
	// gate asserting "the scan was blocked while the successor was published" needs to know, because the
	// waiter may have stopped being blocked long before the publish — maxHold fires and the request proceeds
	// while the hold entry is still sitting in the map, so the counter stays up and the block is over.
	//
	// CurrentHeldWaiters is the gauge that actually answers it: how many requests are blocked RIGHT NOW. A
	// gate can wait for it to rise before acting and require it to still be up afterwards.
	//
	// HoldTimeouts closes the remaining gap. A waiter that timed out and a fresh waiter that arrived in its
	// place would leave the gauge looking unchanged across the window; a timeout during the window says the
	// hold did not hold for all of it.
	s.counters.HeldRequests.Add(1)
	s.counters.CurrentHeldWaiters.Add(1)
	defer s.counters.CurrentHeldWaiters.Add(-1)
	timer := time.NewTimer(s.maxHold)
	defer timer.Stop()
	select {
	case <-ch:
	case <-timer.C:
		s.counters.HoldTimeouts.Add(1)
	}
}

type faultState struct {
	fault     Fault
	remaining int
}

type Options struct {
	// LeaseTTL is how long a resolved access URL stays valid. Set it shorter than a read to exercise the
	// expiry-mid-read gate.
	LeaseTTL time.Duration
	// Token, when non-empty, must be presented to the resolver as a bearer credential.
	Token string
	// PublicBaseURL is the origin a RESOLVED access URL names, when it differs from the listen address.
	//
	// WHY THIS IS NEEDED AT ALL. `BaseURL()` is derived from the listener, and a server told to listen on
	// `0.0.0.0:8099` reports exactly that — so a resolver running in a container would hand back
	// `http://0.0.0.0:8099/object/...`, which is not a host anything can dial and is not the origin the
	// daemon's allowlist names. The resolved URL has to be the origin a CLIENT reaches this server at, which
	// only the caller knows.
	PublicBaseURL string
	// LeasePrefix makes a minted lease id GREPPABLE.
	//
	// Leases are otherwise `l1`, `l2`, ... — fine for an in-process test that compares them directly, and
	// useless to a gate that has to prove a lease never reached disk: `l1` occurs by chance in any few
	// megabytes of binary, so a search for it can only produce false positives. A caller that supplies a
	// high-entropy prefix gets a lease value it can search for EXACTLY, in a media file or a database, and
	// mean something by finding none.
	LeasePrefix string
	TimeoutFor  time.Duration
	// MaxHold bounds how long Hold can block one request. Zero means 15s, which is shorter than the range
	// adapter's default request timeout on purpose.
	MaxHold  time.Duration
	MaxConns int
	// Addr is where to listen. Empty means `127.0.0.1:0`, which is what every in-process test wants: an
	// ephemeral port on loopback that nothing outside the test can reach. The publisher-to-mount gate runs
	// this server in its own container and needs it reachable from the daemon's container, so it sets an
	// explicit address. Defaulting to loopback keeps that an opt-in rather than something a test could get by
	// accident.
	Addr string
}

func New(opts Options) (*Server, error) {
	addr := opts.Addr
	if addr == "" {
		addr = "127.0.0.1:0"
	}
	listener, err := net.Listen("tcp", addr)
	if err != nil {
		return nil, err
	}
	s := &Server{
		listener:      listener,
		objects:       map[string]Object{},
		objectOrdinal: map[string]int{},
		faults:        map[string]*faultState{},
		holds:         map[string]chan struct{}{},
		maxHold:       opts.MaxHold,
		leases:        map[string]time.Time{},
		leaseTTL:      opts.LeaseTTL,
		leasePrefix:   opts.LeasePrefix,
		publicBaseURL: strings.TrimRight(opts.PublicBaseURL, "/"),
		now:           time.Now,
		timeoutFor:    opts.TimeoutFor,
		token:         opts.Token,
		requireAuth:   opts.Token != "",
	}
	if s.leaseTTL == 0 {
		s.leaseTTL = time.Hour
	}
	if s.timeoutFor == 0 {
		s.timeoutFor = 2 * time.Second
	}
	if s.maxHold == 0 {
		// Shorter than the HTTP range adapter's 20s default request timeout, so a forgotten release is a slow
		// read rather than a failed one.
		s.maxHold = 15 * time.Second
	}
	mux := http.NewServeMux()
	mux.HandleFunc("/resolve", s.handleResolve)
	mux.HandleFunc("/object/", s.handleObject)
	mux.HandleFunc("/direct/", s.handleDirect)
	mux.HandleFunc("/counters", s.handleCounters)
	// CONTROL, not traffic. These are how a gate outside this process drives the hold, and like /counters
	// they are deliberately not counted as range requests or resolutions.
	mux.HandleFunc("/control/hold/", func(w http.ResponseWriter, r *http.Request) {
		s.Hold(strings.TrimPrefix(r.URL.Path, "/control/hold/"))
		w.WriteHeader(http.StatusNoContent)
	})
	mux.HandleFunc("/control/release/", func(w http.ResponseWriter, r *http.Request) {
		s.Release(strings.TrimPrefix(r.URL.Path, "/control/release/"))
		w.WriteHeader(http.StatusNoContent)
	})
	// THE LEASE GATES DRIVE THE ENDPOINT FROM OUTSIDE ITS PROCESS, which is the only difference between them
	// and the in-process suites that already exercise every one of these behaviours. `InjectFault` and the
	// lease store are ordinary methods; a gate that runs the endpoint in its own container cannot call them,
	// so they get a control surface — UNCOUNTED, exactly as /counters and the hold controls are, because a
	// control request that incremented a range counter would spend the budget it exists to measure.
	mux.HandleFunc("/control/fault/", func(w http.ResponseWriter, r *http.Request) {
		ref := strings.TrimPrefix(r.URL.Path, "/control/fault/")
		if ref == "" {
			w.WriteHeader(http.StatusBadRequest)
			return
		}
		times := 1
		if raw := r.URL.Query().Get("times"); raw != "" {
			parsed, err := strconv.Atoi(raw)
			if err != nil {
				w.WriteHeader(http.StatusBadRequest)
				return
			}
			times = parsed
		}
		s.InjectFault(ref, Fault(r.URL.Query().Get("fault")), times)
		w.WriteHeader(http.StatusNoContent)
	})
	mux.HandleFunc("/control/expire-leases", func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, map[string]any{"expired": s.ExpireAllLeases()})
	})
	s.server = &http.Server{
		Handler:      mux,
		ReadTimeout:  30 * time.Second,
		WriteTimeout: 30 * time.Second,
		ConnState:    s.trackConn,
	}
	go s.server.Serve(listener)
	return s, nil
}

func (s *Server) trackConn(_ net.Conn, state http.ConnState) {
	switch state {
	case http.StateNew:
		current := s.counters.CurrentConns.Add(1)
		for {
			peak := s.counters.PeakConns.Load()
			if current <= peak || s.counters.PeakConns.CompareAndSwap(peak, current) {
				break
			}
		}
	case http.StateClosed, http.StateHijacked:
		s.counters.CurrentConns.Add(-1)
	}
}

func (s *Server) Close() error {
	_ = s.server.Close()
	return s.listener.Close()
}

func (s *Server) BaseURL() string { return "http://" + s.listener.Addr().String() }

// AdvertisedBaseURL is the origin a RESOLVED access URL names: the caller's public base when it gave one,
// and the listen address otherwise. Every in-process test takes the second branch and is unaffected.
func (s *Server) AdvertisedBaseURL() string {
	if s.publicBaseURL != "" {
		return s.publicBaseURL
	}
	return s.BaseURL()
}

func (s *Server) ResolveURL() string { return s.BaseURL() + "/resolve" }
func (s *Server) DirectURL() string  { return s.BaseURL() + "/direct" }
func (s *Server) Host() string {
	host, _, _ := net.SplitHostPort(s.listener.Addr().String())
	return host
}
func (s *Server) Counters() *Counters { return &s.counters }

// AddObject registers a servable object whose bytes are the deterministic content function.
func (s *Server) AddObject(ref string, size int64) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.objects[ref] = Object{Ref: ref, Size: size}
	s.assignOrdinal(ref)
}

// assignOrdinal gives a newly registered object its place in the per-object byte array. Callers hold s.mu.
// Re-registering a reference keeps its original slot, so a size correction does not shuffle the array under
// a gate that has already taken a snapshot.
func (s *Server) assignOrdinal(ref string) {
	if _, seen := s.objectOrdinal[ref]; seen {
		return
	}
	s.objectOrdinal[ref] = len(s.objectBytes)
	s.objectBytes = append(s.objectBytes, &atomic.Int64{})
	s.objectObserved = append(s.objectObserved, &atomic.Int64{})
	s.objectChunk = append(s.objectChunk, &atomic.Int64{})
	s.objectPartial = append(s.objectPartial, &atomic.Int64{})
	s.objectSmall = append(s.objectSmall, &atomic.Int64{})
	s.objectOversized = append(s.objectOversized, &atomic.Int64{})
}

// AddFileObject registers a servable object whose bytes are a file's. The size is the file's own, read once
// here: a size supplied by the caller could disagree with the file, and every range this server grants is
// computed against it.
func (s *Server) AddFileObject(ref, path string) (int64, error) {
	info, err := os.Stat(path)
	if err != nil {
		return 0, err
	}
	if !info.Mode().IsRegular() {
		return 0, fmt.Errorf("fakeprovider: %s is not a regular file", path)
	}
	if info.Size() <= 0 {
		return 0, fmt.Errorf("fakeprovider: %s is empty", path)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.objects[ref] = Object{Ref: ref, Size: info.Size(), Path: path}
	s.assignOrdinal(ref)
	return info.Size(), nil
}

// BytesOf returns the object's bytes for one range, from the file when it has one and from the deterministic
// content function otherwise. A short read is an error rather than a short slice: this server's entire value
// is that what it says it served is what it served.
func (s *Server) BytesOf(object Object, offset, length int64) ([]byte, error) {
	if object.Path == "" {
		return ObjectBytes(object.Ref, offset, length), nil
	}
	file, err := os.Open(object.Path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	out := make([]byte, length)
	if _, err := io.ReadFull(io.NewSectionReader(file, offset, length), out); err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectFor exposes one registered object, so a gate tool can compute the digests it will later compare
// against without a second idea of where the bytes came from.
func (s *Server) ObjectFor(ref string) (Object, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	object, ok := s.objects[ref]
	return object, ok
}

// CountersSnapshot is the wire shape of Counters. It exists because a gate that runs this server in its own
// container cannot read atomics across a process boundary, and a budget nobody can read is not a budget.
type CountersSnapshot struct {
	Resolutions int64 `json:"resolutions"`
	// RangeRequests is ARRIVALS: counted when a request reaches the handler, before its outcome is known.
	// It is the denominator a request ceiling wants. It is NOT the partition's side — a request in flight at
	// a snapshot is an arrival with no class yet, which is exactly how gate9's partition failed 5 against 4.
	RangeRequests int64 `json:"rangeRequests"`
	// AccountedResponses is the partition's side: requests whose outcome has been recorded, incremented in
	// the same critical section as the class and the bytes. Named for what it counts rather than for HTTP
	// completion, which has not happened yet when it moves.
	AccountedResponses int64 `json:"accountedResponses"`
	// HeldRequests is a lifetime count; CurrentHeldWaiters is how many are blocked at this instant, which is
	// the only one that can support "a request was still blocked while X happened"; HoldTimeouts is how many
	// holds lapsed rather than being released, which is how a gate detects that its window had a gap in it.
	HeldRequests       int64 `json:"heldRequests"`
	CurrentHeldWaiters int64 `json:"currentHeldWaiters"`
	HoldTimeouts       int64 `json:"holdTimeouts"`
	// BytesServed is COMMITTED payload length. The key keeps its historical spelling because three other
	// gates read it and their run records describe exactly this quantity; it is not a delivery figure.
	BytesServed int64 `json:"bytesServed"`
	// ObservedBytes is what `http.ResponseWriter.Write` RETURNED, summed. An APPLICATION-WRITE observation:
	// not peer receipt, not a TCP acknowledgement, not exact wire bytes, not billing.
	ObservedBytes   int64 `json:"observedBytes"`
	CompletedBodies int64 `json:"completedBodies"`
	TruncatedBodies int64 `json:"truncatedBodies"`
	// BodiesInFlight is a GAUGE, published so a caller can WAIT for settlement rather than guess, and so a
	// caller that did not wait is refused rather than answered.
	BodiesInFlight  int64 `json:"bodiesInFlight"`
	Served429       int64 `json:"served429"`
	FullBodyServed  int64 `json:"fullBodyServed"`
	ExpiredRejected int64 `json:"expiredRejected"`
	PeakConcurrent  int64 `json:"peakConcurrent"`
	PeakConns       int64 `json:"peakConns"`
	// Request shape, in four flat size buckets. See Counters.
	//
	// TWO PARTITIONS, AND A CALLER SHOULD CHECK BOTH:
	//
	//	ChunkBytes + SmallBytes + PartialBytes + OversizedBytes                 == BytesServed
	//	Chunk + Small + Partial + Oversized + BodylessResponses (as counts)     == RangeRequests
	//
	// THE SECOND ONE RECONCILES AGAINST BodylessResponses, NOT AGAINST A LIST OF REFUSALS. This comment used
	// to say the counts sum to RangeRequests less Served429 and ExpiredRejected, which was short by every
	// other no-body path — an unknown object, a missing file, a malformed Range, 401, 403, 410, 503, a
	// timeout, a redirect. BodylessResponses covers all of them structurally.
	//
	// Bytes alone are not enough: two responses filed as one leave the byte total intact and the count
	// wrong, and the count is what a request geometry is derived from.
	ChunkResponses     int64 `json:"chunkResponses"`
	ChunkBytes         int64 `json:"chunkBytes"`
	SmallResponses     int64 `json:"smallResponses"`
	SmallBytes         int64 `json:"smallBytes"`
	PartialResponses   int64 `json:"partialResponses"`
	PartialBytes       int64 `json:"partialBytes"`
	OversizedResponses int64 `json:"oversizedResponses"`
	OversizedBytes     int64 `json:"oversizedBytes"`
	BodylessResponses  int64 `json:"bodylessResponses"`
	// ObjectBytes is bytes served per registered object, indexed by the order the caller registered them.
	//
	// THE PARTITION A CALLER SHOULD CHECK: sum(ObjectBytes) == BytesServed. A shortfall means a body was
	// served for a reference this server never registered, which is the only way attribution can go missing.
	//
	// IT CARRIES ONE ORDERING AND NOT THE OTHER, which is the only honest way to say this. The index IS the
	// registration order of objects, deliberately, because that is what makes a position a stable handle
	// across two snapshots. What is absent is any PER-REQUEST temporal ordering: no reference, URL, lease,
	// offset, status or timestamp, and no record of which request came when or in what sequence bytes were
	// asked for. See the field it is built from.
	ObjectBytes []int64 `json:"objectBytes"`
	// ObjectObserved is the APPLICATION-WRITE observation per object, in the SAME order. Readable only once
	// BodiesInFlight is zero.
	ObjectObserved []int64 `json:"objectObserved"`
	// ObjectSizes is each registered object's own length, in the SAME order as ObjectBytes.
	//
	// IT IS HERE SO NOTHING HAS TO PAIR TWO ORDERINGS. The per-object ceiling is a function of the object's
	// size, and the caller's list of sizes is in the caller's order while this array is in registration
	// order. Matching them by position would silently judge one object against another's length — a defect
	// that reports confident per-object verdicts about the wrong objects. The endpoint already knows every
	// size, because the caller told it at registration, so it answers with them and the question does not
	// arise. This reveals nothing the caller did not supply.
	ObjectSizes []int64 `json:"objectSizes"`
	// PER-OBJECT RESPONSE-CLASS COUNTS, in the SAME order as ObjectBytes and ObjectSizes.
	//
	// WHY THEY EXIST. gate9 failed one object at 4.487x of its own length, and identifying which responses
	// were its required noticing that 35,415,553 + 3 x 1,048,576 happened to equal its byte total exactly.
	// That is a coincidence that worked once, not a method: bytes alone cannot say which CLASS a given
	// object's traffic fell into, so the per-object arithmetic the model is built on could not be checked
	// against the object it describes. These four arrays make it observable.
	//
	// THE IDENTITY A CALLER SHOULD CHECK, per object i:
	//
	//	ObjectChunk[i] + ObjectSmall[i] + ObjectPartial[i] + ObjectOversized[i]  ==  its served responses
	//
	// and summed across i, each column equals its aggregate counter.
	ObjectChunk     []int64 `json:"objectChunk"`
	ObjectSmall     []int64 `json:"objectSmall"`
	ObjectPartial   []int64 `json:"objectPartial"`
	ObjectOversized []int64 `json:"objectOversized"`
}

// recordObjectServedLocked attributes one served response to the object it came from, by registration
// ordinal, in both bytes and class. The caller holds s.accounting.
//
// It takes the CLASS recordShape actually chose rather than recomputing it, because two switch statements
// over the same boundaries are how an aggregate and its per-object mirror drift apart.
//
// An unregistered reference cannot reach here with a body — serveRange has already refused it — but if one
// ever did, the bytes stay in the aggregate and are simply unattributed, which a caller detects by the
// attribution partition failing rather than by silently losing them.
// recordObjectObservedLocked attributes what Write RETURNED for one body to its registration ordinal. It is a
// SEPARATE call from the commit above, at a separate moment, because the two numbers are separated by however
// long the write took and by whether the peer stayed to receive it. The caller holds s.accounting.
func (s *Server) recordObjectObservedLocked(ref string, n int64) {
	s.mu.Lock()
	ordinal, known := s.objectOrdinal[ref]
	var observed *atomic.Int64
	if known && ordinal < len(s.objectObserved) {
		observed = s.objectObserved[ordinal]
	}
	s.mu.Unlock()
	if observed == nil {
		return
	}
	observed.Add(n)
}

// WaitForSettlement blocks until no body is between its commit and its observation, or until the budget
// elapses, and answers whether settlement was reached. It is BOUNDED: a loop that waited forever would turn a
// client that never finished into a wedged gate, and a refusal is a better failure than a hang.
func (s *Server) WaitForSettlement(budget time.Duration) bool {
	deadline := time.Now().Add(budget)
	for {
		if s.counters.BodiesInFlight.Load() == 0 {
			return true
		}
		if !time.Now().Before(deadline) {
			return s.counters.BodiesInFlight.Load() == 0
		}
		time.Sleep(5 * time.Millisecond)
	}
}

func (s *Server) recordObjectServedLocked(ref string, n int64, class responseClass) {
	s.mu.Lock()
	ordinal, known := s.objectOrdinal[ref]
	var bytes, classCounter *atomic.Int64
	if known && ordinal < len(s.objectBytes) {
		bytes = s.objectBytes[ordinal]
		switch class {
		case classChunk:
			classCounter = s.objectChunk[ordinal]
		case classSmall:
			classCounter = s.objectSmall[ordinal]
		case classPartial:
			classCounter = s.objectPartial[ordinal]
		case classOversized:
			classCounter = s.objectOversized[ordinal]
		}
	}
	s.mu.Unlock()
	if bytes == nil {
		return
	}
	bytes.Add(n)
	if classCounter != nil {
		classCounter.Add(1)
	}
}

// Snapshot reads the RESPONSE-ACCOUNTING SET under the accounting lock, and everything else independently.
//
// WHAT IS COHERENT, EXACTLY: the four size classes, BytesServed, BodylessResponses, AccountedResponses and
// the per-object columns. Those are the counters that appear together in an assertion, and they are the only
// ones the accounting lock covers.
//
// WHAT IS NOT, AND SAYING SO MATTERS: RangeRequests, the hold counters, Resolutions, the connection peaks and
// the fault tallies all move outside that lock, at their own points in a request's life. A snapshot can
// therefore show an arrival with no accounted response — that is a request in flight, and it is expected.
// The first version of this comment claimed every counter was coherent, which is a larger promise than the
// lock makes and the kind of overstatement this file has had to retract twice.
//
// AN EARLIER VERSION SAID COHERENCE WAS UNNECESSARY ALTOGETHER because each counter is individually atomic
// and each is asserted against its own budget. gate9 falsified that: the request partition failed 5 against
// 4 because a request in flight had been counted as an arrival but not yet classified. Individually atomic
// counters are not a coherent SET, and an assertion relating two of them needs one.
//
// THE LOCK IS THE ONE THE ACCOUNTING PATH TAKES, held there for a few adds and never across a hold, a read
// or a socket write. So a deliberately held request cannot make this hang — which would turn the hold
// primitive into a way to freeze the instrument that measures it.
//
// The per-object columns come from one call for the same reason: taken separately, an object registered in
// between produced arrays of different lengths, and a caller pairing them by index would read one object's
// bytes against the next object's size.
func (s *Server) Snapshot() CountersSnapshot {
	s.accounting.Lock()
	defer s.accounting.Unlock()
	objects, objectSizes := s.objectTotalsAndSizes()
	return CountersSnapshot{
		Resolutions:        s.counters.Resolutions.Load(),
		RangeRequests:      s.counters.RangeRequests.Load(),
		HeldRequests:       s.counters.HeldRequests.Load(),
		CurrentHeldWaiters: s.counters.CurrentHeldWaiters.Load(),
		HoldTimeouts:       s.counters.HoldTimeouts.Load(),
		BytesServed:        s.counters.BytesServed.Load(),
		ObservedBytes:      s.counters.ObservedBytes.Load(),
		CompletedBodies:    s.counters.CompletedBodies.Load(),
		TruncatedBodies:    s.counters.TruncatedBodies.Load(),
		BodiesInFlight:     s.counters.BodiesInFlight.Load(),
		Served429:          s.counters.Served429.Load(),
		FullBodyServed:     s.counters.FullBodyServed.Load(),
		ExpiredRejected:    s.counters.ExpiredRejected.Load(),
		PeakConcurrent:     s.counters.PeakConcurrent.Load(),
		PeakConns:          s.counters.PeakConns.Load(),
		ChunkResponses:     s.counters.ChunkResponses.Load(),
		ChunkBytes:         s.counters.ChunkBytes.Load(),
		SmallResponses:     s.counters.SmallResponses.Load(),
		SmallBytes:         s.counters.SmallBytes.Load(),
		PartialResponses:   s.counters.PartialResponses.Load(),
		PartialBytes:       s.counters.PartialBytes.Load(),
		OversizedResponses: s.counters.OversizedResponses.Load(),
		OversizedBytes:     s.counters.OversizedBytes.Load(),
		ObjectBytes:        objects.bytes,
		ObjectObserved:     objects.observed,
		ObjectSizes:        objectSizes,
		ObjectChunk:        objects.chunk,
		ObjectSmall:        objects.small,
		ObjectPartial:      objects.partial,
		ObjectOversized:    objects.oversized,
		AccountedResponses: s.counters.AccountedResponses.Load(),
		BodylessResponses:  s.counters.BodylessResponses.Load(),
	}
}

// handleCounters serves the snapshot. IT IS NOT COUNTED as a range request or a resolution — a surface that
// perturbed the numbers it reports would make every budget read a little bigger every time somebody looked.
func (s *Server) handleCounters(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, s.Snapshot())
}

// ExpireAllLeases makes every outstanding lease lapse RIGHT NOW.
//
// WHY A GATE NEEDS THIS AND A SHORT TTL IS NOT ENOUGH. G24 asks for a lease that expires DURING a read. A
// short `LeaseTTL` gets there eventually, but only by racing the reader: too long and the read finishes
// first, too short and the lease is already dead before the read starts, and the gate passes or fails on
// timing rather than on behaviour. That is the defect this repository has already paid for twice — a window
// whose verdict depended on which of two things happened first.
//
// So the lapse is an EVENT the gate causes, at the moment of its choosing, between two reads it controls.
// The next ranged request on an outstanding lease is then answered 401 exactly as a naturally lapsed one is —
// the same code path, the same counter — because this does not special-case anything: it moves the recorded
// expiry into the past and lets the ordinary check reject it.
func (s *Server) ExpireAllLeases() int {
	s.mu.Lock()
	defer s.mu.Unlock()
	past := s.now().Add(-time.Hour)
	expired := 0
	for lease := range s.leases {
		if s.leases[lease].After(past) {
			s.leases[lease] = past
			expired++
		}
	}
	return expired
}

// InjectFault applies a fault to the next `times` requests for one object. times <= 0 means "always".
func (s *Server) InjectFault(ref string, fault Fault, times int) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if fault == FaultNone {
		delete(s.faults, ref)
		return
	}
	s.faults[ref] = &faultState{fault: fault, remaining: times}
}

func (s *Server) takeFault(ref string) Fault {
	s.mu.Lock()
	defer s.mu.Unlock()
	state, ok := s.faults[ref]
	if !ok {
		return FaultNone
	}
	if state.remaining > 0 {
		state.remaining--
		if state.remaining == 0 {
			delete(s.faults, ref)
		}
	}
	return state.fault
}

// ObjectBytes is the deterministic content function. Byte i of an object is derived from a digest of the
// reference and the 32-byte window index, so any range can be produced without materialising the object.
func ObjectBytes(ref string, offset, length int64) []byte {
	out := make([]byte, length)
	for i := int64(0); i < length; {
		pos := offset + i
		window := pos / 32
		var seed [8]byte
		binary.BigEndian.PutUint64(seed[:], uint64(window))
		digest := sha256.Sum256(append([]byte(ref+"\x00"), seed[:]...))
		start := pos % 32
		n := int64(copy(out[i:], digest[start:]))
		if n == 0 {
			break
		}
		i += n
	}
	return out
}

func (s *Server) handleResolve(w http.ResponseWriter, r *http.Request) {
	s.counters.Resolutions.Add(1)
	if s.requireAuth {
		if r.Header.Get("Authorization") != "Bearer "+s.token {
			w.WriteHeader(http.StatusUnauthorized)
			return
		}
	}
	var body struct {
		ObjectRef string `json:"objectRef"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	s.mu.Lock()
	_, known := s.objects[body.ObjectRef]
	s.mu.Unlock()
	if !known {
		w.WriteHeader(http.StatusNotFound)
		return
	}
	switch s.takeFaultFor(body.ObjectRef, FaultResolverError, FaultDisallowedHost) {
	case FaultResolverError:
		w.WriteHeader(http.StatusInternalServerError)
		return
	case FaultDisallowedHost:
		// The provider names a host the daemon was never configured to contact. It must not be dialled.
		writeJSON(w, map[string]any{
			"url":             "http://evil.invalid/object/x/" + body.ObjectRef,
			"expiresAtUnixMs": s.now().Add(s.leaseTTL).UnixMilli(),
		})
		return
	}

	lease := s.leasePrefix + "l" + strconv.FormatUint(s.leaseSeq.Add(1), 10)
	expires := s.now().Add(s.leaseTTL)
	s.mu.Lock()
	s.leases[lease] = expires
	s.mu.Unlock()
	writeJSON(w, map[string]any{
		"url":             s.AdvertisedBaseURL() + "/object/" + lease + "/" + body.ObjectRef,
		"headers":         map[string]string{"X-Fake-Lease": lease},
		"expiresAtUnixMs": expires.UnixMilli(),
	})
}

// takeFaultFor consumes the pending fault only when it is one of the listed kinds, so a range-path fault is
// not eaten by a resolver request.
func (s *Server) takeFaultFor(ref string, kinds ...Fault) Fault {
	s.mu.Lock()
	state, ok := s.faults[ref]
	s.mu.Unlock()
	if !ok {
		return FaultNone
	}
	for _, kind := range kinds {
		if state.fault == kind {
			return s.takeFault(ref)
		}
	}
	return FaultNone
}

func writeJSON(w http.ResponseWriter, value any) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(value)
}

func (s *Server) handleDirect(w http.ResponseWriter, r *http.Request) {
	ref := strings.TrimPrefix(r.URL.Path, "/direct/")
	s.serveRange(w, r, ref, "")
}

func (s *Server) handleObject(w http.ResponseWriter, r *http.Request) {
	rest := strings.TrimPrefix(r.URL.Path, "/object/")
	parts := strings.SplitN(rest, "/", 2)
	if len(parts) != 2 {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	s.serveRange(w, r, parts[1], parts[0])
}

func (s *Server) serveRange(w http.ResponseWriter, r *http.Request, ref, lease string) {
	current := s.counters.CurrentConcurrent.Add(1)
	for {
		peak := s.counters.PeakConcurrent.Load()
		if current <= peak || s.counters.PeakConcurrent.CompareAndSwap(peak, current) {
			break
		}
	}
	defer s.counters.CurrentConcurrent.Add(-1)
	s.counters.RangeRequests.Add(1)

	// EVERY RANGED REQUEST LANDS IN EXACTLY ONE BUCKET, INCLUDING THE ONES THAT SERVE NOTHING.
	//
	// THE DEFECT THIS CLOSES. The first version of the request partition reconciled the three size buckets
	// against RangeRequests by adding back Served429 and ExpiredRejected — and this function returns without
	// a body in a dozen other places: an unknown object, a missing file, a malformed Range, 401, 403, 410,
	// 503, a timeout, a redirect. Every one of those made the partition short, so the gate that claimed to
	// account for every request would have failed on any of them while its note insisted it was complete.
	// Enumerating the known faults is exactly the fix that goes stale the next time a fault is added.
	//
	// So the accounting is structural rather than enumerated: one deferred increment that fires unless a body
	// was classified. A new no-body branch is counted correctly the day it is written, by nobody.
	bodyClassified := false
	defer func() {
		if bodyClassified {
			return
		}
		// NO BODY WAS SERVED, so the outcome is recorded here — and Bodyless and AccountedResponses move together
		// under the same lock the classified path uses, which is what makes the partition exact.
		s.accounting.Lock()
		s.counters.BodylessResponses.Add(1)
		s.counters.AccountedResponses.Add(1)
		s.accounting.Unlock()
	}()
	// serveBody is the ONE way a body is recorded AND the one way it is written. Routing every body-producing
	// branch through it is what keeps the flag and the buckets from drifting apart.
	//
	// IT COUNTS BEFORE IT WRITES, AND THAT ORDER IS THE POINT.
	//
	// THE DEFECT THIS CLOSES. Every branch used to write the body and then record it. A client that read its
	// response to completion could therefore observe the counters BEFORE the handler had counted the very
	// response it had just finished reading — the handler had returned from Write, but not yet reached the
	// increment. The test that drives all four size classes caught it under `-race` with a second package
	// running alongside: the fourth response was still uncounted when the snapshot was taken, and the "other"
	// bucket read zero. The window is small, but a counter snapshot taken at a phase boundary is exactly the
	// case where it matters: the last response of a scan would be attributed to the NEXT window, making one
	// budget look cheaper and the following one dearer, with the totals still summing correctly.
	//
	// COUNTING FIRST MEANS THE COMMITTED COUNTERS DESCRIBE WHAT THE ENDPOINT UNDERTOOK TO SERVE rather than
	// anything about what became of the bytes. That is the honest reading for a conservative budget: the
	// handler committed to a length, and a body abandoned part-way is still work the handler set out to do.
	// WHAT IT IS NOT is any statement that those bytes were written, let alone received — a committed payload
	// length proves neither, which is exactly what ObservedBytes exists to measure separately.
	//
	// AND IT IS NOT, ON ITS OWN, A DELIVERY FIGURE — WHICH THIS PACKAGE ONCE LET A REPORT PRETEND. Every
	// branch here used to end `_, _ = w.Write(payload)`, discarding both the count and the error, so the only
	// byte number that existed was the committed one. `internal/fakewebdav` had the same shape and a report
	// built on it concluded something about delivery that its instrument could not support. So the write's
	// OWN return is now recorded too, in a second phase, and the two are never conflated.
	//
	// It also takes the payload rather than a length, so a branch cannot record a size that disagrees with
	// what it wrote.
	serveBody := func(payload []byte) {
		n := int64(len(payload))
		// PHASE ONE — COMMIT. ONE CRITICAL SECTION FOR THE WHOLE ACCOUNTING SET, and it closes BEFORE the
		// write. Count-before-write is preserved — the bytes cannot reach the client until every counter
		// describing them has moved — and the counters move as a SET, so a snapshot cannot catch this
		// response half recorded. The in-flight gauge rises in the SAME critical section, so a snapshot can
		// never see a committed length whose body is neither in flight nor observed.
		s.accounting.Lock()
		s.counters.BytesServed.Add(n)
		class := s.counters.recordShape(n)
		s.recordObjectServedLocked(ref, n, class)
		s.counters.AccountedResponses.Add(1)
		s.counters.BodiesInFlight.Add(1)
		bodyClassified = true
		s.accounting.Unlock()

		// PHASE TWO — OBSERVE. The write's own return value and error, both used. `written` is what this
		// handler successfully handed to the HTTP stack; see ObservedBytes for what that does and does not
		// mean. The lock is taken again for a few adds and is never held across the write itself.
		written, writeErr := w.Write(payload)
		if written < 0 {
			written = 0
		}
		s.accounting.Lock()
		s.counters.ObservedBytes.Add(int64(written))
		s.recordObjectObservedLocked(ref, int64(written))
		if writeErr == nil && int64(written) == n {
			s.counters.CompletedBodies.Add(1)
		} else {
			// A SHORT WRITE AND AN ERRORED ONE ARE THE SAME FINDING and are not separated: the endpoint
			// cannot tell an abandoned read from a broken pipe and would be guessing if it named one.
			s.counters.TruncatedBodies.Add(1)
		}
		s.counters.BodiesInFlight.Add(-1)
		s.accounting.Unlock()
	}

	// The request has arrived and is counted; holding it blocks the READER, which is the point.
	s.waitForHold(ref)

	s.mu.Lock()
	object, known := s.objects[ref]
	expires, leaseKnown := s.leases[lease]
	s.mu.Unlock()
	if !known {
		w.WriteHeader(http.StatusNotFound)
		return
	}
	if lease != "" {
		if !leaseKnown || !s.now().Before(expires) {
			// The normal end of a signed URL's life.
			s.counters.ExpiredRejected.Add(1)
			w.WriteHeader(http.StatusUnauthorized)
			return
		}
	}

	fault := s.takeFault(ref)
	switch fault {
	case Fault401:
		w.WriteHeader(http.StatusUnauthorized)
		return
	case Fault403:
		w.WriteHeader(http.StatusForbidden)
		return
	case Fault410:
		w.WriteHeader(http.StatusGone)
		return
	case Fault429:
		s.counters.Served429.Add(1)
		w.Header().Set("Retry-After", "1")
		w.WriteHeader(http.StatusTooManyRequests)
		return
	case Fault503:
		w.WriteHeader(http.StatusServiceUnavailable)
		return
	case FaultTimeout:
		time.Sleep(s.timeoutFor)
		return
	case FaultRedirect:
		w.Header().Set("Location", s.BaseURL()+"/direct/"+ref)
		w.WriteHeader(http.StatusFound)
		return
	}

	start, end, ok := parseRange(r.Header.Get("Range"), object.Size)
	if !ok {
		w.WriteHeader(http.StatusRequestedRangeNotSatisfiable)
		return
	}
	length := end - start + 1
	data, err := s.BytesOf(object, start, length)
	if err != nil {
		// A file-backed object whose file went away. This is the server's fault, not the client's, and saying
		// so as a 500 keeps it from being mistaken for a range the client asked for wrongly.
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	switch fault {
	case FaultFullBodyOnRange:
		// 200 with the whole object. A daemon that reads this body downloads the file to answer a probe.
		s.counters.FullBodyServed.Add(1)
		full, err := s.BytesOf(object, 0, object.Size)
		if err != nil {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Length", strconv.FormatInt(object.Size, 10))
		w.WriteHeader(http.StatusOK)
		serveBody(full)
		return
	case FaultMalformedRange:
		w.Header().Set("Content-Range", "octets "+strconv.FormatInt(start, 10))
	case FaultMismatchedRange:
		w.Header().Set("Content-Range", fmt.Sprintf("bytes %d-%d/%d", start+1, end+1, object.Size))
	case FaultWrongTotalSize:
		w.Header().Set("Content-Range", fmt.Sprintf("bytes %d-%d/%d", start, end, object.Size+4096))
	default:
		w.Header().Set("Content-Range", fmt.Sprintf("bytes %d-%d/%d", start, end, object.Size))
	}

	switch fault {
	case FaultShortBody:
		short := data[:len(data)/2]
		w.Header().Set("Content-Length", strconv.FormatInt(int64(len(data)), 10))
		w.WriteHeader(http.StatusPartialContent)
		serveBody(short)
		return
	case FaultDelayedClose:
		// No Content-Length, so the response is chunked; the body is correct and complete, but the terminal
		// chunk is late.
		w.WriteHeader(http.StatusPartialContent)
		serveBody(data)
		if flusher, ok := w.(http.Flusher); ok {
			flusher.Flush()
		}
		time.Sleep(s.timeoutFor)
		return
	case FaultLongBody:
		// Deliberately synthetic filler: this fault is about a body longer than the granted range, and where
		// the surplus bytes came from is not what is under test. Reading past EOF of a file-backed object to
		// obtain them would turn the fault into an I/O error instead.
		long := append(data, ObjectBytes(ref, end+1, 64)...)
		w.WriteHeader(http.StatusPartialContent)
		serveBody(long)
		return
	}

	w.Header().Set("Content-Length", strconv.FormatInt(length, 10))
	w.WriteHeader(http.StatusPartialContent)
	serveBody(data)
}

func parseRange(value string, size int64) (int64, int64, bool) {
	if !strings.HasPrefix(value, "bytes=") {
		return 0, 0, false
	}
	spec := strings.TrimPrefix(value, "bytes=")
	dash := strings.Index(spec, "-")
	if dash <= 0 {
		return 0, 0, false
	}
	start, err := strconv.ParseInt(spec[:dash], 10, 64)
	if err != nil {
		return 0, 0, false
	}
	end, err := strconv.ParseInt(spec[dash+1:], 10, 64)
	if err != nil {
		return 0, 0, false
	}
	if start < 0 || end < start || start >= size {
		return 0, 0, false
	}
	if end >= size {
		end = size - 1
	}
	return start, end, true
}

// objectTotalsAndSizes returns bytes-served and length for every registered object, in registration order,
// read under a SINGLE lock so the two arrays always describe the same set of objects.
//
// A caller pairs them by index. If they could be taken at different moments, a registration in between would
// make index i mean two different objects in the two arrays, and every per-object verdict after it would be
// judging the wrong pair. The counters themselves are atomic; only the slice headers need the lock.
// It returns the class columns too, for the same reason and in the same order.
func (s *Server) objectTotalsAndSizes() (perObject, []int64) {
	s.mu.Lock()
	count := len(s.objectBytes)
	bytesCounters := make([]*atomic.Int64, count)
	chunkCounters := make([]*atomic.Int64, count)
	smallCounters := make([]*atomic.Int64, count)
	partialCounters := make([]*atomic.Int64, count)
	oversizedCounters := make([]*atomic.Int64, count)
	observedCounters := make([]*atomic.Int64, count)
	copy(bytesCounters, s.objectBytes)
	copy(observedCounters, s.objectObserved)
	copy(chunkCounters, s.objectChunk)
	copy(smallCounters, s.objectSmall)
	copy(partialCounters, s.objectPartial)
	copy(oversizedCounters, s.objectOversized)
	sizes := make([]int64, count)
	for ref, ordinal := range s.objectOrdinal {
		if ordinal < count {
			sizes[ordinal] = s.objects[ref].Size
		}
	}
	s.mu.Unlock()

	load := func(counters []*atomic.Int64) []int64 {
		out := make([]int64, len(counters))
		for i, counter := range counters {
			out[i] = counter.Load()
		}
		return out
	}
	return perObject{
		bytes:     load(bytesCounters),
		observed:  load(observedCounters),
		chunk:     load(chunkCounters),
		small:     load(smallCounters),
		partial:   load(partialCounters),
		oversized: load(oversizedCounters),
	}, sizes
}

// perObject is the ordinal-aligned per-object view, carried as one value so the columns cannot be returned
// from different moments and paired by a caller who assumes they match.
type perObject struct {
	bytes     []int64
	observed  []int64
	chunk     []int64
	small     []int64
	partial   []int64
	oversized []int64
}
