// Package fakeprovider is a deterministic HTTP Range endpoint with an access resolver, counters and fault
// injection. It is the only "provider" the automated gates ever contact.
//
// IT IS DETERMINISTIC ON PURPOSE. Object bytes are a pure function of the object reference and the offset, so
// a test can assert the exact bytes a read returned without shipping fixtures, and two runs of the same gate
// compare the same numbers. Every counter here is what the amplification budget is measured against.
package fakeprovider

import (
	"crypto/sha256"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

// Fault is an injected misbehaviour, applied to one object.
type Fault string

const (
	FaultNone Fault = ""
	// FaultFullBodyOnRange answers a ranged request with 200 and the whole object. Accepting one is the most
	// expensive protocol failure available here.
	FaultFullBodyOnRange Fault = "full-body-on-range"
	FaultMalformedRange  Fault = "malformed-content-range"
	FaultMismatchedRange Fault = "mismatched-content-range"
	FaultShortBody       Fault = "short-body"
	FaultWrongTotalSize  Fault = "wrong-total-size"
	FaultLongBody        Fault = "long-body"
	Fault401             Fault = "status-401"
	Fault403             Fault = "status-403"
	Fault410             Fault = "status-410"
	Fault429             Fault = "status-429"
	Fault503             Fault = "status-503"
	FaultTimeout         Fault = "timeout"
	FaultRedirect        Fault = "redirect"
	FaultDisallowedHost  Fault = "disallowed-host"
	FaultResolverError   Fault = "resolver-error"
	// FaultDelayedClose serves the CORRECT bytes for the granted range, chunked, and then delays its terminal
	// chunk. A client that insists on reading to EOF before accepting the range stalls here for the whole
	// request timeout even though the server did nothing wrong.
	FaultDelayedClose Fault = "delayed-close"
)

// Object is one served byte stream.
//
// Path, when non-empty, makes the object FILE BACKED: the bytes come from that file rather than from the
// deterministic content function. The synthetic function is what every amplification and protocol gate wants,
// because it lets a test assert exact bytes without shipping a fixture. It is useless to a gate that needs a
// reader which DECODES what it fetched — a media server probes a container header, and pseudo-random bytes do
// not have one. So a file-backed object exists for exactly that case, and the file it names is generated by
// the gate that uses it, on the machine that runs it, from a synthetic signal.
type Object struct {
	Ref  string
	Size int64
	Path string
}

// Counters are read by the gates. Every one of them is a number a budget is asserted against.
type Counters struct {
	Resolutions   atomic.Int64
	RangeRequests atomic.Int64
	// HeldRequests is a LIFETIME count of requests that entered a hold. CurrentHeldWaiters is how many are
	// blocked right now, and HoldTimeouts counts holds that lapsed instead of being released.
	HeldRequests       atomic.Int64
	CurrentHeldWaiters atomic.Int64
	HoldTimeouts       atomic.Int64
	BytesServed        atomic.Int64
	Served429          atomic.Int64
	FullBodyServed     atomic.Int64
	ExpiredRejected    atomic.Int64
	PeakConcurrent     atomic.Int64
	CurrentConcurrent  atomic.Int64
	PeakConns          atomic.Int64
	CurrentConns       atomic.Int64

	// REQUEST SHAPE, IN THREE BUCKETS AND NOTHING ELSE.
	//
	// WHY THIS EXISTS. A gate measured 32,505,856 bytes over 10 ranged requests for one object and could say
	// nothing about the mix: 7.75 demand blocks is not a whole number of anything, so the total is some
	// combination of full 4 MiB blocks and smaller probe or tail reads. A budget derived from a total that
	// cannot be decomposed is a budget derived from a coincidence, and the honest response is to measure the
	// shape rather than to pick a multiplier that clears the observation.
	//
	// WHY THREE FLAT BUCKETS AND NOT A LOG. Anything per-request is a record of what was read and when, and
	// this endpoint serves media on behalf of a product whose whole argument is about not leaking access
	// material. Cumulative counts and byte totals in fixed buckets answer "what mix of sizes was served"
	// without retaining a single URL, header, lease, offset or ordering. There is nothing here to redact
	// because there is nothing here to identify.
	ChunkResponses atomic.Int64
	ChunkBytes     atomic.Int64
	SmallResponses atomic.Int64
	SmallBytes     atomic.Int64
	OtherResponses atomic.Int64
	OtherBytes     atomic.Int64
	// BodylessResponses is every ranged request that returned WITHOUT a body: an unknown object, a missing
	// file, a malformed Range, and each of the injected refusals — 401, 403, 410, 429, 503, a timeout, a
	// redirect. It exists so the request partition is an equation rather than an approximation:
	//
	//	ChunkResponses + SmallResponses + OtherResponses + BodylessResponses == RangeRequests
	//
	// IT IS COUNTED STRUCTURALLY, NOT ENUMERATED. `serveRange` defers an increment that fires unless a body
	// was classified, so a no-body branch added tomorrow is accounted for by nobody having to remember it.
	// The first draft of this reconciliation added back only Served429 and ExpiredRejected and was short by
	// a dozen paths, while its gate name claimed to cover every request.
	BodylessResponses atomic.Int64
}

// The bucket boundaries, and both are read off the daemon rather than chosen here.
const (
	// chunkResponseBytes is readpath.DefaultConfig().ChunkBytes: the daemon's demand block. A response of
	// exactly this size is one full block.
	chunkResponseBytes = 4 * 1024 * 1024
	// smallResponseBytes is manifest.ProbeWindowBytes: one scan window. At or under this, a response is a
	// probe-sized read rather than a demand block.
	smallResponseBytes = 1024 * 1024
)

// recordShape files one served response into exactly one bucket. It is called wherever bytes are counted, so
// the buckets always sum to BytesServed and a caller can check that they do.
func (c *Counters) recordShape(n int64) {
	switch {
	case n == chunkResponseBytes:
		c.ChunkResponses.Add(1)
		c.ChunkBytes.Add(n)
	case n <= smallResponseBytes:
		c.SmallResponses.Add(1)
		c.SmallBytes.Add(n)
	default:
		c.OtherResponses.Add(1)
		c.OtherBytes.Add(n)
	}
}

// Server is the fake endpoint.
type Server struct {
	listener net.Listener
	server   *http.Server
	counters Counters

	mu sync.Mutex
	// objects by reference
	objects map[string]Object
	// faults by reference; remaining>0 means "apply this many more times, then stop"
	faults        map[string]*faultState
	leaseTTL      time.Duration
	leasePrefix   string
	publicBaseURL string
	leaseSeq      atomic.Uint64
	leases        map[string]time.Time
	now           func() time.Time
	timeoutFor    time.Duration
	// requireAuth makes the resolver refuse a request with no bearer credential.
	requireAuth bool
	token       string
	// holds blocks range requests for one object until released. See Hold.
	holds   map[string]chan struct{}
	maxHold time.Duration
}

// Hold makes every subsequent ranged request for one object BLOCK until Release, or until maxHold elapses.
//
// WHY A GATE NEEDS THIS. Proving that something happened "while a library scan was running" against a real
// media server is otherwise a race: a four-entry scan takes a couple of seconds, and the handshake that
// observes it, publishes, and re-checks costs about as long. Retrying until the timing works is not evidence,
// it is a coin flip with a loop around it.
//
// Holding a provider read turns the timing into a fact. A scanner probing an entry whose bytes are not yet
// cached blocks in the read, so the scan is DETERMINISTICALLY still running for as long as the gate keeps the
// hold — long enough to observe it running, publish into it, and observe it running again afterwards. The
// hold is then released and the scan completes normally.
//
// THE BOUND IS NOT OPTIONAL. A gate that crashed between Hold and Release would otherwise wedge the daemon's
// read until its own request timeout, and every later assertion would fail for an unrelated reason. maxHold
// is deliberately shorter than the daemon's default request timeout so a forgotten release degrades into a
// slow read rather than a failed one.
func (s *Server) Hold(ref string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, exists := s.holds[ref]; !exists {
		s.holds[ref] = make(chan struct{})
	}
}

// Release lets any held request for one object proceed. Releasing something not held is not an error.
func (s *Server) Release(ref string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if ch, exists := s.holds[ref]; exists {
		close(ch)
		delete(s.holds, ref)
	}
}

// waitForHold blocks a request while its object is held, and counts the fact that it blocked.
func (s *Server) waitForHold(ref string) {
	s.mu.Lock()
	ch, held := s.holds[ref]
	s.mu.Unlock()
	if !held {
		return
	}
	// THREE NUMBERS, BECAUSE ONE OF THEM ANSWERS A QUESTION THE OTHERS CANNOT.
	//
	// HeldRequests is a lifetime counter: it says a request entered a hold AT SOME POINT. That is not what a
	// gate asserting "the scan was blocked while the successor was published" needs to know, because the
	// waiter may have stopped being blocked long before the publish — maxHold fires and the request proceeds
	// while the hold entry is still sitting in the map, so the counter stays up and the block is over.
	//
	// CurrentHeldWaiters is the gauge that actually answers it: how many requests are blocked RIGHT NOW. A
	// gate can wait for it to rise before acting and require it to still be up afterwards.
	//
	// HoldTimeouts closes the remaining gap. A waiter that timed out and a fresh waiter that arrived in its
	// place would leave the gauge looking unchanged across the window; a timeout during the window says the
	// hold did not hold for all of it.
	s.counters.HeldRequests.Add(1)
	s.counters.CurrentHeldWaiters.Add(1)
	defer s.counters.CurrentHeldWaiters.Add(-1)
	timer := time.NewTimer(s.maxHold)
	defer timer.Stop()
	select {
	case <-ch:
	case <-timer.C:
		s.counters.HoldTimeouts.Add(1)
	}
}

type faultState struct {
	fault     Fault
	remaining int
}

type Options struct {
	// LeaseTTL is how long a resolved access URL stays valid. Set it shorter than a read to exercise the
	// expiry-mid-read gate.
	LeaseTTL time.Duration
	// Token, when non-empty, must be presented to the resolver as a bearer credential.
	Token string
	// PublicBaseURL is the origin a RESOLVED access URL names, when it differs from the listen address.
	//
	// WHY THIS IS NEEDED AT ALL. `BaseURL()` is derived from the listener, and a server told to listen on
	// `0.0.0.0:8099` reports exactly that — so a resolver running in a container would hand back
	// `http://0.0.0.0:8099/object/...`, which is not a host anything can dial and is not the origin the
	// daemon's allowlist names. The resolved URL has to be the origin a CLIENT reaches this server at, which
	// only the caller knows.
	PublicBaseURL string
	// LeasePrefix makes a minted lease id GREPPABLE.
	//
	// Leases are otherwise `l1`, `l2`, ... — fine for an in-process test that compares them directly, and
	// useless to a gate that has to prove a lease never reached disk: `l1` occurs by chance in any few
	// megabytes of binary, so a search for it can only produce false positives. A caller that supplies a
	// high-entropy prefix gets a lease value it can search for EXACTLY, in a media file or a database, and
	// mean something by finding none.
	LeasePrefix string
	TimeoutFor  time.Duration
	// MaxHold bounds how long Hold can block one request. Zero means 15s, which is shorter than the range
	// adapter's default request timeout on purpose.
	MaxHold  time.Duration
	MaxConns int
	// Addr is where to listen. Empty means `127.0.0.1:0`, which is what every in-process test wants: an
	// ephemeral port on loopback that nothing outside the test can reach. The publisher-to-mount gate runs
	// this server in its own container and needs it reachable from the daemon's container, so it sets an
	// explicit address. Defaulting to loopback keeps that an opt-in rather than something a test could get by
	// accident.
	Addr string
}

func New(opts Options) (*Server, error) {
	addr := opts.Addr
	if addr == "" {
		addr = "127.0.0.1:0"
	}
	listener, err := net.Listen("tcp", addr)
	if err != nil {
		return nil, err
	}
	s := &Server{
		listener:      listener,
		objects:       map[string]Object{},
		faults:        map[string]*faultState{},
		holds:         map[string]chan struct{}{},
		maxHold:       opts.MaxHold,
		leases:        map[string]time.Time{},
		leaseTTL:      opts.LeaseTTL,
		leasePrefix:   opts.LeasePrefix,
		publicBaseURL: strings.TrimRight(opts.PublicBaseURL, "/"),
		now:           time.Now,
		timeoutFor:    opts.TimeoutFor,
		token:         opts.Token,
		requireAuth:   opts.Token != "",
	}
	if s.leaseTTL == 0 {
		s.leaseTTL = time.Hour
	}
	if s.timeoutFor == 0 {
		s.timeoutFor = 2 * time.Second
	}
	if s.maxHold == 0 {
		// Shorter than the HTTP range adapter's 20s default request timeout, so a forgotten release is a slow
		// read rather than a failed one.
		s.maxHold = 15 * time.Second
	}
	mux := http.NewServeMux()
	mux.HandleFunc("/resolve", s.handleResolve)
	mux.HandleFunc("/object/", s.handleObject)
	mux.HandleFunc("/direct/", s.handleDirect)
	mux.HandleFunc("/counters", s.handleCounters)
	// CONTROL, not traffic. These are how a gate outside this process drives the hold, and like /counters
	// they are deliberately not counted as range requests or resolutions.
	mux.HandleFunc("/control/hold/", func(w http.ResponseWriter, r *http.Request) {
		s.Hold(strings.TrimPrefix(r.URL.Path, "/control/hold/"))
		w.WriteHeader(http.StatusNoContent)
	})
	mux.HandleFunc("/control/release/", func(w http.ResponseWriter, r *http.Request) {
		s.Release(strings.TrimPrefix(r.URL.Path, "/control/release/"))
		w.WriteHeader(http.StatusNoContent)
	})
	s.server = &http.Server{
		Handler:      mux,
		ReadTimeout:  30 * time.Second,
		WriteTimeout: 30 * time.Second,
		ConnState:    s.trackConn,
	}
	go s.server.Serve(listener)
	return s, nil
}

func (s *Server) trackConn(_ net.Conn, state http.ConnState) {
	switch state {
	case http.StateNew:
		current := s.counters.CurrentConns.Add(1)
		for {
			peak := s.counters.PeakConns.Load()
			if current <= peak || s.counters.PeakConns.CompareAndSwap(peak, current) {
				break
			}
		}
	case http.StateClosed, http.StateHijacked:
		s.counters.CurrentConns.Add(-1)
	}
}

func (s *Server) Close() error {
	_ = s.server.Close()
	return s.listener.Close()
}

func (s *Server) BaseURL() string { return "http://" + s.listener.Addr().String() }

// AdvertisedBaseURL is the origin a RESOLVED access URL names: the caller's public base when it gave one,
// and the listen address otherwise. Every in-process test takes the second branch and is unaffected.
func (s *Server) AdvertisedBaseURL() string {
	if s.publicBaseURL != "" {
		return s.publicBaseURL
	}
	return s.BaseURL()
}

func (s *Server) ResolveURL() string { return s.BaseURL() + "/resolve" }
func (s *Server) DirectURL() string  { return s.BaseURL() + "/direct" }
func (s *Server) Host() string {
	host, _, _ := net.SplitHostPort(s.listener.Addr().String())
	return host
}
func (s *Server) Counters() *Counters { return &s.counters }

// AddObject registers a servable object whose bytes are the deterministic content function.
func (s *Server) AddObject(ref string, size int64) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.objects[ref] = Object{Ref: ref, Size: size}
}

// AddFileObject registers a servable object whose bytes are a file's. The size is the file's own, read once
// here: a size supplied by the caller could disagree with the file, and every range this server grants is
// computed against it.
func (s *Server) AddFileObject(ref, path string) (int64, error) {
	info, err := os.Stat(path)
	if err != nil {
		return 0, err
	}
	if !info.Mode().IsRegular() {
		return 0, fmt.Errorf("fakeprovider: %s is not a regular file", path)
	}
	if info.Size() <= 0 {
		return 0, fmt.Errorf("fakeprovider: %s is empty", path)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.objects[ref] = Object{Ref: ref, Size: info.Size(), Path: path}
	return info.Size(), nil
}

// BytesOf returns the object's bytes for one range, from the file when it has one and from the deterministic
// content function otherwise. A short read is an error rather than a short slice: this server's entire value
// is that what it says it served is what it served.
func (s *Server) BytesOf(object Object, offset, length int64) ([]byte, error) {
	if object.Path == "" {
		return ObjectBytes(object.Ref, offset, length), nil
	}
	file, err := os.Open(object.Path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	out := make([]byte, length)
	if _, err := io.ReadFull(io.NewSectionReader(file, offset, length), out); err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectFor exposes one registered object, so a gate tool can compute the digests it will later compare
// against without a second idea of where the bytes came from.
func (s *Server) ObjectFor(ref string) (Object, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	object, ok := s.objects[ref]
	return object, ok
}

// CountersSnapshot is the wire shape of Counters. It exists because a gate that runs this server in its own
// container cannot read atomics across a process boundary, and a budget nobody can read is not a budget.
type CountersSnapshot struct {
	Resolutions   int64 `json:"resolutions"`
	RangeRequests int64 `json:"rangeRequests"`
	// HeldRequests is a lifetime count; CurrentHeldWaiters is how many are blocked at this instant, which is
	// the only one that can support "a request was still blocked while X happened"; HoldTimeouts is how many
	// holds lapsed rather than being released, which is how a gate detects that its window had a gap in it.
	HeldRequests       int64 `json:"heldRequests"`
	CurrentHeldWaiters int64 `json:"currentHeldWaiters"`
	HoldTimeouts       int64 `json:"holdTimeouts"`
	BytesServed        int64 `json:"bytesServed"`
	Served429          int64 `json:"served429"`
	FullBodyServed     int64 `json:"fullBodyServed"`
	ExpiredRejected    int64 `json:"expiredRejected"`
	PeakConcurrent     int64 `json:"peakConcurrent"`
	PeakConns          int64 `json:"peakConns"`
	// Request shape, in three flat buckets. See Counters.
	//
	// TWO PARTITIONS, AND A CALLER SHOULD CHECK BOTH. The bucket BYTES sum to BytesServed, and the bucket
	// RESPONSE COUNTS sum to the number of ranged requests that served a body — which is RangeRequests less
	// the ones refused without one (Served429, ExpiredRejected). Bytes alone are not enough: two responses
	// filed as one leave the byte total intact and the count wrong, and the count is what a geometry is
	// derived from.
	ChunkResponses    int64 `json:"chunkResponses"`
	ChunkBytes        int64 `json:"chunkBytes"`
	SmallResponses    int64 `json:"smallResponses"`
	SmallBytes        int64 `json:"smallBytes"`
	OtherResponses    int64 `json:"otherResponses"`
	OtherBytes        int64 `json:"otherBytes"`
	BodylessResponses int64 `json:"bodylessResponses"`
}

// Snapshot reads every counter. It is not atomic across counters and does not need to be: each one is
// asserted against its own budget.
func (s *Server) Snapshot() CountersSnapshot {
	return CountersSnapshot{
		Resolutions:        s.counters.Resolutions.Load(),
		RangeRequests:      s.counters.RangeRequests.Load(),
		HeldRequests:       s.counters.HeldRequests.Load(),
		CurrentHeldWaiters: s.counters.CurrentHeldWaiters.Load(),
		HoldTimeouts:       s.counters.HoldTimeouts.Load(),
		BytesServed:        s.counters.BytesServed.Load(),
		Served429:          s.counters.Served429.Load(),
		FullBodyServed:     s.counters.FullBodyServed.Load(),
		ExpiredRejected:    s.counters.ExpiredRejected.Load(),
		PeakConcurrent:     s.counters.PeakConcurrent.Load(),
		PeakConns:          s.counters.PeakConns.Load(),
		ChunkResponses:     s.counters.ChunkResponses.Load(),
		ChunkBytes:         s.counters.ChunkBytes.Load(),
		SmallResponses:     s.counters.SmallResponses.Load(),
		SmallBytes:         s.counters.SmallBytes.Load(),
		OtherResponses:     s.counters.OtherResponses.Load(),
		OtherBytes:         s.counters.OtherBytes.Load(),
		BodylessResponses:  s.counters.BodylessResponses.Load(),
	}
}

// handleCounters serves the snapshot. IT IS NOT COUNTED as a range request or a resolution — a surface that
// perturbed the numbers it reports would make every budget read a little bigger every time somebody looked.
func (s *Server) handleCounters(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, s.Snapshot())
}

// InjectFault applies a fault to the next `times` requests for one object. times <= 0 means "always".
func (s *Server) InjectFault(ref string, fault Fault, times int) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if fault == FaultNone {
		delete(s.faults, ref)
		return
	}
	s.faults[ref] = &faultState{fault: fault, remaining: times}
}

func (s *Server) takeFault(ref string) Fault {
	s.mu.Lock()
	defer s.mu.Unlock()
	state, ok := s.faults[ref]
	if !ok {
		return FaultNone
	}
	if state.remaining > 0 {
		state.remaining--
		if state.remaining == 0 {
			delete(s.faults, ref)
		}
	}
	return state.fault
}

// ObjectBytes is the deterministic content function. Byte i of an object is derived from a digest of the
// reference and the 32-byte window index, so any range can be produced without materialising the object.
func ObjectBytes(ref string, offset, length int64) []byte {
	out := make([]byte, length)
	for i := int64(0); i < length; {
		pos := offset + i
		window := pos / 32
		var seed [8]byte
		binary.BigEndian.PutUint64(seed[:], uint64(window))
		digest := sha256.Sum256(append([]byte(ref+"\x00"), seed[:]...))
		start := pos % 32
		n := int64(copy(out[i:], digest[start:]))
		if n == 0 {
			break
		}
		i += n
	}
	return out
}

func (s *Server) handleResolve(w http.ResponseWriter, r *http.Request) {
	s.counters.Resolutions.Add(1)
	if s.requireAuth {
		if r.Header.Get("Authorization") != "Bearer "+s.token {
			w.WriteHeader(http.StatusUnauthorized)
			return
		}
	}
	var body struct {
		ObjectRef string `json:"objectRef"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	s.mu.Lock()
	_, known := s.objects[body.ObjectRef]
	s.mu.Unlock()
	if !known {
		w.WriteHeader(http.StatusNotFound)
		return
	}
	switch s.takeFaultFor(body.ObjectRef, FaultResolverError, FaultDisallowedHost) {
	case FaultResolverError:
		w.WriteHeader(http.StatusInternalServerError)
		return
	case FaultDisallowedHost:
		// The provider names a host the daemon was never configured to contact. It must not be dialled.
		writeJSON(w, map[string]any{
			"url":             "http://evil.invalid/object/x/" + body.ObjectRef,
			"expiresAtUnixMs": s.now().Add(s.leaseTTL).UnixMilli(),
		})
		return
	}

	lease := s.leasePrefix + "l" + strconv.FormatUint(s.leaseSeq.Add(1), 10)
	expires := s.now().Add(s.leaseTTL)
	s.mu.Lock()
	s.leases[lease] = expires
	s.mu.Unlock()
	writeJSON(w, map[string]any{
		"url":             s.AdvertisedBaseURL() + "/object/" + lease + "/" + body.ObjectRef,
		"headers":         map[string]string{"X-Fake-Lease": lease},
		"expiresAtUnixMs": expires.UnixMilli(),
	})
}

// takeFaultFor consumes the pending fault only when it is one of the listed kinds, so a range-path fault is
// not eaten by a resolver request.
func (s *Server) takeFaultFor(ref string, kinds ...Fault) Fault {
	s.mu.Lock()
	state, ok := s.faults[ref]
	s.mu.Unlock()
	if !ok {
		return FaultNone
	}
	for _, kind := range kinds {
		if state.fault == kind {
			return s.takeFault(ref)
		}
	}
	return FaultNone
}

func writeJSON(w http.ResponseWriter, value any) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(value)
}

func (s *Server) handleDirect(w http.ResponseWriter, r *http.Request) {
	ref := strings.TrimPrefix(r.URL.Path, "/direct/")
	s.serveRange(w, r, ref, "")
}

func (s *Server) handleObject(w http.ResponseWriter, r *http.Request) {
	rest := strings.TrimPrefix(r.URL.Path, "/object/")
	parts := strings.SplitN(rest, "/", 2)
	if len(parts) != 2 {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	s.serveRange(w, r, parts[1], parts[0])
}

func (s *Server) serveRange(w http.ResponseWriter, r *http.Request, ref, lease string) {
	current := s.counters.CurrentConcurrent.Add(1)
	for {
		peak := s.counters.PeakConcurrent.Load()
		if current <= peak || s.counters.PeakConcurrent.CompareAndSwap(peak, current) {
			break
		}
	}
	defer s.counters.CurrentConcurrent.Add(-1)
	s.counters.RangeRequests.Add(1)

	// EVERY RANGED REQUEST LANDS IN EXACTLY ONE BUCKET, INCLUDING THE ONES THAT SERVE NOTHING.
	//
	// THE DEFECT THIS CLOSES. The first version of the request partition reconciled the three size buckets
	// against RangeRequests by adding back Served429 and ExpiredRejected — and this function returns without
	// a body in a dozen other places: an unknown object, a missing file, a malformed Range, 401, 403, 410,
	// 503, a timeout, a redirect. Every one of those made the partition short, so the gate that claimed to
	// account for every request would have failed on any of them while its note insisted it was complete.
	// Enumerating the known faults is exactly the fix that goes stale the next time a fault is added.
	//
	// So the accounting is structural rather than enumerated: one deferred increment that fires unless a body
	// was classified. A new no-body branch is counted correctly the day it is written, by nobody.
	bodyClassified := false
	defer func() {
		if !bodyClassified {
			s.counters.BodylessResponses.Add(1)
		}
	}()
	// serveBody is the ONE way a body is recorded. Routing every body-producing branch through it is what
	// keeps the flag and the buckets from drifting apart.
	serveBody := func(n int64) {
		s.counters.BytesServed.Add(n)
		s.counters.recordShape(n)
		bodyClassified = true
	}

	// The request has arrived and is counted; holding it blocks the READER, which is the point.
	s.waitForHold(ref)

	s.mu.Lock()
	object, known := s.objects[ref]
	expires, leaseKnown := s.leases[lease]
	s.mu.Unlock()
	if !known {
		w.WriteHeader(http.StatusNotFound)
		return
	}
	if lease != "" {
		if !leaseKnown || !s.now().Before(expires) {
			// The normal end of a signed URL's life.
			s.counters.ExpiredRejected.Add(1)
			w.WriteHeader(http.StatusUnauthorized)
			return
		}
	}

	fault := s.takeFault(ref)
	switch fault {
	case Fault401:
		w.WriteHeader(http.StatusUnauthorized)
		return
	case Fault403:
		w.WriteHeader(http.StatusForbidden)
		return
	case Fault410:
		w.WriteHeader(http.StatusGone)
		return
	case Fault429:
		s.counters.Served429.Add(1)
		w.Header().Set("Retry-After", "1")
		w.WriteHeader(http.StatusTooManyRequests)
		return
	case Fault503:
		w.WriteHeader(http.StatusServiceUnavailable)
		return
	case FaultTimeout:
		time.Sleep(s.timeoutFor)
		return
	case FaultRedirect:
		w.Header().Set("Location", s.BaseURL()+"/direct/"+ref)
		w.WriteHeader(http.StatusFound)
		return
	}

	start, end, ok := parseRange(r.Header.Get("Range"), object.Size)
	if !ok {
		w.WriteHeader(http.StatusRequestedRangeNotSatisfiable)
		return
	}
	length := end - start + 1
	data, err := s.BytesOf(object, start, length)
	if err != nil {
		// A file-backed object whose file went away. This is the server's fault, not the client's, and saying
		// so as a 500 keeps it from being mistaken for a range the client asked for wrongly.
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	switch fault {
	case FaultFullBodyOnRange:
		// 200 with the whole object. A daemon that reads this body downloads the file to answer a probe.
		s.counters.FullBodyServed.Add(1)
		full, err := s.BytesOf(object, 0, object.Size)
		if err != nil {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Length", strconv.FormatInt(object.Size, 10))
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write(full)
		serveBody(object.Size)
		return
	case FaultMalformedRange:
		w.Header().Set("Content-Range", "octets "+strconv.FormatInt(start, 10))
	case FaultMismatchedRange:
		w.Header().Set("Content-Range", fmt.Sprintf("bytes %d-%d/%d", start+1, end+1, object.Size))
	case FaultWrongTotalSize:
		w.Header().Set("Content-Range", fmt.Sprintf("bytes %d-%d/%d", start, end, object.Size+4096))
	default:
		w.Header().Set("Content-Range", fmt.Sprintf("bytes %d-%d/%d", start, end, object.Size))
	}

	switch fault {
	case FaultShortBody:
		short := data[:len(data)/2]
		w.Header().Set("Content-Length", strconv.FormatInt(int64(len(data)), 10))
		w.WriteHeader(http.StatusPartialContent)
		_, _ = w.Write(short)
		serveBody(int64(len(short)))
		return
	case FaultDelayedClose:
		// No Content-Length, so the response is chunked; the body is correct and complete, but the terminal
		// chunk is late.
		w.WriteHeader(http.StatusPartialContent)
		_, _ = w.Write(data)
		if flusher, ok := w.(http.Flusher); ok {
			flusher.Flush()
		}
		serveBody(int64(len(data)))
		time.Sleep(s.timeoutFor)
		return
	case FaultLongBody:
		// Deliberately synthetic filler: this fault is about a body longer than the granted range, and where
		// the surplus bytes came from is not what is under test. Reading past EOF of a file-backed object to
		// obtain them would turn the fault into an I/O error instead.
		long := append(data, ObjectBytes(ref, end+1, 64)...)
		w.WriteHeader(http.StatusPartialContent)
		_, _ = w.Write(long)
		serveBody(int64(len(long)))
		return
	}

	w.Header().Set("Content-Length", strconv.FormatInt(length, 10))
	w.WriteHeader(http.StatusPartialContent)
	_, _ = w.Write(data)
	serveBody(length)
}

func parseRange(value string, size int64) (int64, int64, bool) {
	if !strings.HasPrefix(value, "bytes=") {
		return 0, 0, false
	}
	spec := strings.TrimPrefix(value, "bytes=")
	dash := strings.Index(spec, "-")
	if dash <= 0 {
		return 0, 0, false
	}
	start, err := strconv.ParseInt(spec[:dash], 10, 64)
	if err != nil {
		return 0, 0, false
	}
	end, err := strconv.ParseInt(spec[dash+1:], 10, 64)
	if err != nil {
		return 0, 0, false
	}
	if start < 0 || end < start || start >= size {
		return 0, 0, false
	}
	if end >= size {
		end = size - 1
	}
	return start, end, true
}
