//go:build linux

// Command fakerange runs the deterministic HTTP Range endpoint as a standalone process.
//
// IT IS A GATE TOOL AND IT NEVER SHIPS, exactly like ./cmd/mkfixture. The production Dockerfile builds only
// ./cmd/projectiond, so this binary exists solely inside the pinned toolchain image. It exists because the
// publisher-to-mount gate has to read a REMOTE projected entry through the mount, and a remote entry needs an
// endpoint that answers ranged requests correctly — which `internal/fakeprovider` already is, and which the
// rest of the Phase 1 gates already measure their amplification budgets against.
//
// IT IS NOT A PROVIDER ADAPTER AND IT CONTACTS NOTHING. Object bytes are a pure function of the object
// reference and the offset, so the gate can assert the exact bytes a read returned without shipping a fixture,
// and two runs compare the same digests. There is no named provider here, no real endpoint, and no network
// call leaves this process — the wiring gate refuses any Go file in this module that names one.
//
// WHAT IT WRITES. A small JSON document naming, per object: the size, the sha256 of the WHOLE object, and the
// byte-identity probe digests at the contract's fixed offsets. The gate registers those probes as the control
// plane's assertion about the byte stream and hashes the whole-object digest against what it read through the
// mount — a digest recorded OUTSIDE the thing being verified, which is the only kind worth comparing against.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"syscall"

	"github.com/cdb8457/streaming-catalog-authority/projectiond/internal/fakeprovider"
	"github.com/cdb8457/streaming-catalog-authority/projectiond/internal/manifest"
)

type probeOut struct {
	Position string `json:"position"`
	Offset   int64  `json:"offset"`
	Length   int64  `json:"length"`
	SHA256   string `json:"sha256"`
}

type objectOut struct {
	Ref    string     `json:"ref"`
	Size   int64      `json:"size"`
	SHA256 string     `json:"sha256"`
	Probes []probeOut `json:"probes"`
}

func main() {
	addr := flag.String("addr", "0.0.0.0:8099", "address to listen on")
	emit := flag.String("emit", "", "write the object descriptor JSON here")
	// A HIGH-ENTROPY LEASE PREFIX, so a gate can prove an access lease never reached disk by searching for
	// its exact value. Default leases are `l1`, `l2`, ... which occur by chance in any binary.
	leasePrefix := flag.String("lease-prefix", "", "prefix minted lease ids with this, to make them greppable")
	// The origin a RESOLVED url names. Listening on 0.0.0.0 means the listener cannot describe itself in a
	// way any client could dial, so a resolver mode server has to be told what it is reachable as.
	publicBase := flag.String("public-base-url", "", "origin to advertise in resolved access URLs")
	// HOW LONG A HELD RANGED REQUEST MAY BLOCK, AND WHY A CALLER GETS TO SAY.
	//
	// The default is 15s, chosen to sit under the range adapter's 20s per-request timeout. That is the right
	// default for a gate that arms a hold and releases it inside the same phase. It is NOT right for the
	// three-server concurrency gate, whose hold is a RENDEZVOUS the scanners arrive at one at a time: there
	// the relevant ceiling is `PROJECTIOND_READ_POLICY.FIRST_BYTE_DEADLINE_MS`, which is 10s, because a held
	// response that has not begun by then is abandoned and the read FAILS. A gate that crashed between arm
	// and release would then be manufacturing the very defect it claims to measure.
	//
	// So the bound is a flag, and that gate passes something comfortably under ten seconds. Zero keeps the
	// package default.
	maxHold := flag.Duration("max-hold", 0, "how long a held ranged request may block; 0 keeps the default")
	var objects objectList
	var files fileList
	flag.Var(&objects, "object", "ref:size, repeatable — bytes from the deterministic content function")
	flag.Var(&files, "file-object", "ref=path, repeatable — bytes from a file the gate generated")
	flag.Parse()

	if len(objects) == 0 && len(files) == 0 {
		fail("at least one --object ref:size or --file-object ref=path is required")
	}

	server, err := fakeprovider.New(fakeprovider.Options{
		Addr: *addr, LeasePrefix: *leasePrefix, PublicBaseURL: *publicBase, MaxHold: *maxHold,
	})
	if err != nil {
		fail(err.Error())
	}
	defer server.Close()

	out := make([]objectOut, 0, len(objects)+len(files))
	for _, object := range objects {
		server.AddObject(object.ref, object.size)
		out = append(out, describe(server, object.ref))
	}
	// A FILE-BACKED OBJECT, for the one gate that needs the fetched bytes to DECODE. Everything else here
	// wants the deterministic content function; a media server probing a container header does not, because
	// pseudo-random bytes have no container header. The file is generated by the gate, on the machine that
	// runs it, from a synthetic signal — nothing is downloaded and nothing is shipped.
	for _, file := range files {
		if _, err := server.AddFileObject(file.ref, file.path); err != nil {
			fail(err.Error())
		}
		out = append(out, describe(server, file.ref))
	}

	if *emit != "" {
		encoded, err := json.MarshalIndent(out, "", "  ")
		if err != nil {
			fail(err.Error())
		}
		if err := os.WriteFile(*emit, append(encoded, '\n'), 0o644); err != nil {
			fail(err.Error())
		}
	}

	fmt.Printf("fakerange listening on %s with %d object(s)\n", *addr, len(objects)+len(files))
	signals := make(chan os.Signal, 1)
	signal.Notify(signals, syscall.SIGINT, syscall.SIGTERM)
	<-signals
	fmt.Println("fakerange stopping")
}

// describe computes the whole-object digest and the probe digests at the contract's own fixed offsets, THROUGH
// THE SERVER'S OWN BYTE ACCESSOR. Going through the server rather than re-deriving the bytes here is what
// keeps one idea of where an object's bytes come from: a second one would eventually disagree, and the gate
// would be comparing a digest of what this tool imagined against bytes a reader actually got.
func describe(server *fakeprovider.Server, ref string) objectOut {
	object, ok := server.ObjectFor(ref)
	if !ok {
		fail("object " + ref + " was not registered")
	}
	whole, err := server.BytesOf(object, 0, object.Size)
	if err != nil {
		fail(err.Error())
	}
	wholeDigest := sha256.Sum256(whole)
	probes := make([]probeOut, 0, 3)
	for _, slot := range manifest.ProbeOffsetsFor(object.Size) {
		window, err := server.BytesOf(object, slot.Offset, slot.Length)
		if err != nil {
			fail(err.Error())
		}
		digest := sha256.Sum256(window)
		probes = append(probes, probeOut{
			Position: slot.Position, Offset: slot.Offset, Length: slot.Length,
			SHA256: hex.EncodeToString(digest[:]),
		})
	}
	return objectOut{
		Ref: ref, Size: object.Size, SHA256: hex.EncodeToString(wholeDigest[:]), Probes: probes,
	}
}

type objectSpec struct {
	ref  string
	size int64
}

type objectList []objectSpec

func (l *objectList) String() string { return fmt.Sprintf("%d objects", len(*l)) }

func (l *objectList) Set(value string) error {
	// Split on the LAST colon: an object reference may contain one, a size may not.
	index := strings.LastIndex(value, ":")
	if index <= 0 {
		return fmt.Errorf("an object is ref:size")
	}
	size, err := strconv.ParseInt(value[index+1:], 10, 64)
	if err != nil || size <= 0 {
		return fmt.Errorf("an object size is a positive integer")
	}
	*l = append(*l, objectSpec{ref: value[:index], size: size})
	return nil
}

type fileSpec struct {
	ref  string
	path string
}

type fileList []fileSpec

func (l *fileList) String() string { return fmt.Sprintf("%d file objects", len(*l)) }

func (l *fileList) Set(value string) error {
	// Split on the FIRST '=': a path may contain one, an object reference may not — the registry's own CHECK
	// already refuses the characters that would make one ambiguous.
	index := strings.Index(value, "=")
	if index <= 0 || index == len(value)-1 {
		return fmt.Errorf("a file object is ref=path")
	}
	*l = append(*l, fileSpec{ref: value[:index], path: value[index+1:]})
	return nil
}

func fail(message string) {
	fmt.Fprintln(os.Stderr, "fakerange: "+message)
	os.Exit(1)
}
