import {
  PROJECTION_DEGRADED_REASONS,
  PROJECTION_GENERATION_INTENTS,
  PROJECTION_LIMITS,
  PROJECTION_MANIFEST_FORMAT,
  PROJECTION_MANIFEST_VERSION,
  PROJECTION_PROBE_PLAN,
  PROJECTION_SHRINK_GUARD,
  PROJECTION_SOURCE_KINDS,
  PROJECTION_VISIBILITY_STATES,
} from '../core/projection/manifest-v1.js';
import {
  PROJECTIOND_ACCESS_RESOLUTION,
  PROJECTIOND_ADMISSION_LIMITS,
  PROJECTIOND_CACHE_POLICY,
  PROJECTIOND_CIRCUIT_BREAKER,
  PROJECTIOND_CONTRACT_VERSION,
  PROJECTIOND_ERROR_MAP,
  PROJECTIOND_HANDLE_BINDING,
  PROJECTIOND_OPERATIONS,
  PROJECTIOND_PLATFORM_SUPPORT,
  PROJECTIOND_RANGE_RULES,
  PROJECTIOND_READ_POLICY,
  PROJECTIOND_READAHEAD_POLICY,
  PROJECTIOND_RETRY_CLASSES,
  PROJECTIOND_SECRET_AND_EGRESS_POLICY,
  PROJECTION_PHASE_1_BUDGETS,
} from '../core/projection/runtime-contract.js';

// Projection Phase 1 — the one document both languages read.
//
// WHY THIS EXISTS. `projectiond` is written in Go and has to enforce the same deadlines, caps, error mapping
// and probe plan the TypeScript contract freezes. Copying those numbers into Go by hand is how two sides of a
// boundary drift: nobody notices until a gate that measures one of them is asserting against the other's
// idea of it. So the contract is EXPORTED, committed, embedded in the daemon, and checked from both ends —
// the TypeScript suite refuses a stale file, and the Go suite refuses a constant that disagrees with it.
//
// IT IS DERIVED, NOT AUTHORED. Every value here comes from the frozen objects above. There is no number in
// this file, which is what makes it impossible for the export to be right while the contract is wrong.

export const PROJECTION_CONTRACT_EXPORT_FORMAT = 'catalog-authority.projection-contract-export';
export const PROJECTION_CONTRACT_EXPORT_VERSION = 1;

/** The relative path the daemon embeds. Both the writer and the drift check read it from here. */
export const PROJECTION_CONTRACT_EXPORT_PATH = 'projectiond/internal/contract/contract.generated.json';

export function buildProjectionContractExport(): Record<string, unknown> {
  return {
    format: PROJECTION_CONTRACT_EXPORT_FORMAT,
    version: PROJECTION_CONTRACT_EXPORT_VERSION,
    note: 'Generated by `npm run ops:projection-contract-export`. Do not edit by hand; edit the frozen '
      + 'contracts in src/core/projection/ and regenerate.',
    manifest: {
      format: PROJECTION_MANIFEST_FORMAT,
      version: PROJECTION_MANIFEST_VERSION,
      limits: { ...PROJECTION_LIMITS },
      probePlan: { ...PROJECTION_PROBE_PLAN, OFFSETS: [...PROJECTION_PROBE_PLAN.OFFSETS] },
      shrinkGuard: { ...PROJECTION_SHRINK_GUARD },
      visibilityStates: [...PROJECTION_VISIBILITY_STATES],
      sourceKinds: [...PROJECTION_SOURCE_KINDS],
      degradedReasons: [...PROJECTION_DEGRADED_REASONS],
      generationIntents: [...PROJECTION_GENERATION_INTENTS],
    },
    runtime: {
      contractVersion: PROJECTIOND_CONTRACT_VERSION,
      operations: { ...PROJECTIOND_OPERATIONS },
      errorMap: { ...PROJECTIOND_ERROR_MAP },
      readPolicy: { ...PROJECTIOND_READ_POLICY },
      retryClasses: {
        retryable: [...PROJECTIOND_RETRY_CLASSES.retryable],
        'access-refresh-then-retry': [...PROJECTIOND_RETRY_CLASSES['access-refresh-then-retry']],
        terminal: [...PROJECTIOND_RETRY_CLASSES.terminal],
      },
      accessResolution: {
        ...PROJECTIOND_ACCESS_RESOLUTION,
        LEASE_NEVER_IN: [...PROJECTIOND_ACCESS_RESOLUTION.LEASE_NEVER_IN],
        PINNED_ACROSS_REFRESH: [...PROJECTIOND_ACCESS_RESOLUTION.PINNED_ACROSS_REFRESH],
      },
      rangeRules: { ...PROJECTIOND_RANGE_RULES },
      admissionLimits: { ...PROJECTIOND_ADMISSION_LIMITS },
      circuitBreaker: { ...PROJECTIOND_CIRCUIT_BREAKER },
      cachePolicy: {
        probePrefix: { ...PROJECTIOND_CACHE_POLICY.probePrefix },
        playback: { ...PROJECTIOND_CACHE_POLICY.playback },
      },
      readaheadPolicy: { ...PROJECTIOND_READAHEAD_POLICY },
      handleBinding: {
        ...PROJECTIOND_HANDLE_BINDING,
        BINDS_TO: [...PROJECTIOND_HANDLE_BINDING.BINDS_TO],
      },
      secretAndEgressPolicy: {
        ...PROJECTIOND_SECRET_AND_EGRESS_POLICY,
        TOKEN_NEVER_IN: [...PROJECTIOND_SECRET_AND_EGRESS_POLICY.TOKEN_NEVER_IN],
        ACCESS_MATERIAL_NEVER_IN: [...PROJECTIOND_SECRET_AND_EGRESS_POLICY.ACCESS_MATERIAL_NEVER_IN],
        PROVIDER_EGRESS: { ...PROJECTIOND_SECRET_AND_EGRESS_POLICY.PROVIDER_EGRESS },
        MEDIA_SERVER_EGRESS: { ...PROJECTIOND_SECRET_AND_EGRESS_POLICY.MEDIA_SERVER_EGRESS },
      },
      platformSupport: {
        PRODUCTION: [...PROJECTIOND_PLATFORM_SUPPORT.PRODUCTION],
        DEVELOPMENT_ONLY: [...PROJECTIOND_PLATFORM_SUPPORT.DEVELOPMENT_ONLY],
        NOT_PROVABLE_OFF_LINUX: [...PROJECTIOND_PLATFORM_SUPPORT.NOT_PROVABLE_OFF_LINUX],
      },
      phase1Budgets: { ...PROJECTION_PHASE_1_BUDGETS },
    },
  };
}

/** The exact bytes the committed file must contain. Two spaces, a trailing newline, key order as authored. */
export function renderProjectionContractExport(): string {
  return `${JSON.stringify(buildProjectionContractExport(), null, 2)}\n`;
}
