import { createHash } from 'node:crypto';

// Local, non-live blocker taxonomy index. A declared catalogue of every blocker/problem code the Phase 230
// local tooling can emit, mapped to the op that raises it and grouped by a derived category. It verifies
// the catalogue is internally consistent (well-formed UPPER_SNAKE codes, no duplicate code+op pairs, every
// entry attributed to an op). It is a pure declaration + check; it performs no promotion, never touches the
// real Movies root, never contacts Jellyfin, and authorizes nothing live.

export interface BlockerEntry { readonly code: string; readonly op: string; }

// Declared catalogue. A code may appear under more than one op (e.g. a shared leak code); each code+op
// pair is listed once. Kept in sync with the gate DAG by the closure-hygiene gate.
const BLOCKERS: readonly BlockerEntry[] = [
  { code: 'PROMOTION_APPROVAL_REQUIRED', op: 'approval' },
  { code: 'PROMOTION_APPROVAL_MISMATCH', op: 'approval' },
  { code: 'PROMOTION_VISIBILITY_REQUIRED', op: 'promotion' },
  { code: 'PROMOTION_TARGET_FORBIDDEN', op: 'promotion' },
  { code: 'REHEARSAL_FAIL', op: 'rehearsal' },
  { code: 'EVIDENCE_DIGEST_MISMATCH', op: 'evidence-review' },
  { code: 'RAW_PATH_LEAK_SUSPECTED', op: 'evidence-review' },
  { code: 'PROMOTION_MATCHES_APPROVAL', op: 'readiness' },
  { code: 'OBSERVED_JELLYFIN_STATE', op: 'readiness' },
  { code: 'READINESS_NOT_READY', op: 'acceptance-seal' },
  { code: 'ACCEPTANCE_REJECTED', op: 'acceptance-seal' },
  { code: 'MATRIX_FAIL', op: 'rehearsal-matrix' },
  { code: 'PROMOTION_EVIDENCE_SELF_DIGEST_MISMATCH', op: 'artifact-integrity' },
  { code: 'REVIEW_TO_PROMOTION_MISMATCH', op: 'artifact-integrity' },
  { code: 'ACCEPTANCE_PACKET_STATUS_INVALID', op: 'artifact-schema' },
  { code: 'ACCEPTANCE_NOT_SEALED', op: 'handoff' },
  { code: 'INTEGRITY_NOT_OK', op: 'handoff' },
  { code: 'MATRIX_NOT_PASS', op: 'dashboard' },
  { code: 'SCHEMA_NOT_OK', op: 'dashboard' },
  { code: 'HANDOFF_NOT_READY', op: 'dashboard' },
  { code: 'BUNDLE_NOT_ALL_GREEN', op: 'fixture-bundle' },
  { code: 'RAW_PATH_IN_BUNDLE', op: 'fixture-bundle' },
  { code: 'BUNDLE_SELF_DIGEST_MISMATCH', op: 'bundle-replay' },
  { code: 'MANIFEST_STAGE_MISMATCH', op: 'bundle-replay' },
  { code: 'BUNDLE_NOT_READY', op: 'evidence-packet' },
  { code: 'REPLAY_MISSING', op: 'evidence-packet' },
  { code: 'REPLAY_NOT_OK', op: 'evidence-packet' },
  { code: 'REVIEWED_COMMIT_INVALID', op: 'review-transcript' },
  { code: 'TEST_FAILED', op: 'review-transcript' },
  { code: 'CYCLE_DETECTED', op: 'gate-dag' },
  { code: 'UNKNOWN_DEPENDENCY', op: 'gate-dag' },
  { code: 'CHANGELOG_COMMIT_INVALID', op: 'changelog' },
  { code: 'RAW_PATH_LEAK_SUSPECTED', op: 'changelog' },
  { code: 'LEDGER_MISSING', op: 'archive-manifest' },
  { code: 'DAG_MISSING', op: 'archive-manifest' },
  { code: 'EVIDENCE_MISSING', op: 'archive-manifest' },
  { code: 'TRANSCRIPT_MISSING', op: 'archive-manifest' },
  { code: 'LEDGER_INCOMPLETE', op: 'archive-manifest' },
  { code: 'DAG_NOT_ACYCLIC', op: 'archive-manifest' },
  { code: 'EVIDENCE_NOT_COMPLETE', op: 'archive-manifest' },
  { code: 'TRANSCRIPT_NOT_CLEAN', op: 'archive-manifest' },
  { code: 'LEDGER_DIGEST_MISMATCH', op: 'archive-manifest' },
  { code: 'DAG_DIGEST_MISMATCH', op: 'archive-manifest' },
  { code: 'EVIDENCE_DIGEST_MISMATCH', op: 'archive-manifest' },
  { code: 'TRANSCRIPT_DIGEST_MISMATCH', op: 'archive-manifest' },
  { code: 'ARCHIVE_NOT_READY', op: 'archive-manifest' },
  { code: 'EVIDENCE_LEDGER_MISMATCH', op: 'archive-manifest' },
  { code: 'TRANSCRIPT_LEDGER_MISMATCH', op: 'archive-manifest' },
  { code: 'ACCEPTANCE_META_INCOMPLETE', op: 'acceptance-meta' },
  { code: 'INJECTION_EXECUTION_DETECTED', op: 'injection-corpus' },
  { code: 'INJECTION_LIVE_CALL_DETECTED', op: 'injection-corpus' },
  { code: 'REVIEW_BUNDLE_BLOCKED', op: 'review-bundle' },
  { code: 'ARCHIVE_EVIDENCE_MISMATCH', op: 'review-bundle' },
  { code: 'ARCHIVE_TRANSCRIPT_MISMATCH', op: 'review-bundle' },
  { code: 'ARCHIVE_LEDGER_MISMATCH', op: 'review-bundle' },
  { code: 'ARCHIVE_DAG_MISMATCH', op: 'review-bundle' },
  { code: 'OP_NOT_FULLY_MAPPED', op: 'closure' },
  { code: 'GATE_REFERENCES_NON_LOCAL_SUITE', op: 'closure' },
  { code: 'FORBIDDEN_LIVE_HOOK', op: 'live-boundary' },
  { code: 'MISSING_BOUNDARY_LANGUAGE', op: 'live-boundary' },
  { code: 'MATRIX_INCONSISTENT', op: 'consistency-matrix' },
  { code: 'MATRIX_INCOMPLETE', op: 'consistency-matrix' },
  { code: 'DIGEST_MISMATCH', op: 'self-digest-verifier' },
  { code: 'UNRECOGNIZED_REPORT', op: 'self-digest-verifier' },
  { code: 'CONTRACT_VIOLATION', op: 'cli-contract' },
  { code: 'RAW_PATH_LEAK', op: 'cli-contract' },
  { code: 'NON_DETERMINISTIC', op: 'determinism' },
  { code: 'INSUFFICIENT_SAMPLES', op: 'determinism' },
  { code: 'TAXONOMY_INCONSISTENT', op: 'blocker-taxonomy' },
  { code: 'MALFORMED_CODE', op: 'blocker-taxonomy' },
  { code: 'MISSING_OP', op: 'blocker-taxonomy' },
  { code: 'DUPLICATE_ENTRY', op: 'blocker-taxonomy' },
  { code: 'REVIEW_BUNDLE_MISSING', op: 'final-summary' },
  { code: 'REVIEW_BUNDLE_INVALID', op: 'final-summary' },
  { code: 'REVIEW_BUNDLE_NOT_READY', op: 'final-summary' },
  { code: 'MATRIX_INVALID', op: 'final-summary' },
  { code: 'MATRIX_NOT_CONSISTENT', op: 'final-summary' },
  { code: 'SELF_DIGEST_INVALID', op: 'final-summary' },
  { code: 'SELF_DIGEST_NOT_VERIFIED', op: 'final-summary' },
  { code: 'TAXONOMY_INVALID', op: 'final-summary' },
  { code: 'TAXONOMY_NOT_CONSISTENT', op: 'final-summary' },
  { code: 'TRANSCRIPT_MISSING', op: 'final-summary' },
  { code: 'TRANSCRIPT_INVALID', op: 'final-summary' },
  { code: 'TRANSCRIPT_NOT_CLEAN', op: 'final-summary' },
  { code: 'REVIEWED_COMMIT_INVALID', op: 'final-summary' },
  { code: 'TEST_RESULTS_INVALID', op: 'final-summary' },
  { code: 'HYGIENE_VIOLATION', op: 'closure-hygiene' },
  { code: 'UNCATALOGUED_BLOCKER', op: 'closure-hygiene' },
  { code: 'UNKNOWN_TAXONOMY_OP', op: 'closure-hygiene' },
  { code: 'REGISTRY_NOT_WIRED', op: 'closure-hygiene' },
  { code: 'REPORT_NOT_IN_SELF_DIGEST_REGISTRY', op: 'closure-hygiene' },
  { code: 'CLI_NOT_CONTRACT_CONFORMANT', op: 'closure-hygiene' },
  { code: 'CORPUS_BREACHED', op: 'negative-evidence-corpus' },
  { code: 'RELEASE_CHECKLIST_BLOCKED', op: 'release-checklist' },
  { code: 'FINAL_SUMMARY_MISSING', op: 'release-checklist' },
  { code: 'FINAL_SUMMARY_INVALID', op: 'release-checklist' },
  { code: 'FINAL_SUMMARY_NOT_READY', op: 'release-checklist' },
  { code: 'NEGATIVE_CORPUS_MISSING', op: 'release-checklist' },
  { code: 'NEGATIVE_CORPUS_INVALID', op: 'release-checklist' },
  { code: 'NEGATIVE_CORPUS_BREACHED', op: 'release-checklist' },
  { code: 'CLOSURE_HYGIENE_MISSING', op: 'release-checklist' },
  { code: 'CLOSURE_HYGIENE_INVALID', op: 'release-checklist' },
  { code: 'CLOSURE_HYGIENE_NOT_OK', op: 'release-checklist' },
  { code: 'SELF_DIGEST_MISSING', op: 'release-checklist' },
  { code: 'SELF_DIGEST_INVALID', op: 'release-checklist' },
  { code: 'SELF_DIGEST_NOT_VERIFIED', op: 'release-checklist' },
  { code: 'REVIEW_BUNDLE_MISSING', op: 'release-checklist' },
  { code: 'REVIEW_BUNDLE_INVALID', op: 'release-checklist' },
  { code: 'REVIEW_BUNDLE_NOT_READY', op: 'release-checklist' },
  { code: 'TRANSCRIPT_MISSING', op: 'release-checklist' },
  { code: 'TRANSCRIPT_INVALID', op: 'release-checklist' },
  { code: 'TRANSCRIPT_NOT_CLEAN', op: 'release-checklist' },
  { code: 'TRANSCRIPT_BUNDLE_MISMATCH', op: 'release-checklist' },
  { code: 'COMMIT_BINDING_MISMATCH', op: 'release-checklist' },
  { code: 'TEST_RESULTS_BINDING_MISMATCH', op: 'release-checklist' },
  { code: 'REQUIRED_DIGEST_MISSING', op: 'release-checklist' },
  { code: 'REQUIRED_DIGEST_INVALID', op: 'release-checklist' },
  { code: 'MERGE_DRY_RUN_BLOCKED', op: 'merge-readiness' },
  { code: 'RELEASE_CHECKLIST_MISSING', op: 'merge-readiness' },
  { code: 'RELEASE_CHECKLIST_INVALID', op: 'merge-readiness' },
  { code: 'RELEASE_CHECKLIST_NOT_CLEARED', op: 'merge-readiness' },
  { code: 'MERGE_CONTEXT_MISSING', op: 'merge-readiness' },
  { code: 'MERGE_CONTEXT_INVALID', op: 'merge-readiness' },
  { code: 'FINAL_SUMMARY_MISSING', op: 'merge-readiness' },
  { code: 'FINAL_SUMMARY_INVALID', op: 'merge-readiness' },
  { code: 'FINAL_SUMMARY_NOT_READY', op: 'merge-readiness' },
  { code: 'FINAL_SUMMARY_BINDING_MISMATCH', op: 'merge-readiness' },
  { code: 'CHECKLIST_BINDING_INCOMPLETE', op: 'merge-readiness' },
  { code: 'BRANCH_MISSING', op: 'provenance-diff' },
  { code: 'BASE_MISSING', op: 'provenance-diff' },
  { code: 'HEAD_MISSING', op: 'provenance-diff' },
  { code: 'COMMIT_SHA_MALFORMED', op: 'provenance-diff' },
  { code: 'RAW_PATH_LEAK', op: 'provenance-diff' },
  { code: 'TRANSCRIPT_MISSING', op: 'provenance-diff' },
  { code: 'TRANSCRIPT_INVALID', op: 'provenance-diff' },
  { code: 'HEAD_REVIEWED_COMMIT_MISMATCH', op: 'provenance-diff' },
  { code: 'REVIEWED_COMMIT_NOT_IN_RANGE', op: 'provenance-diff' },
  { code: 'STALE_ARTIFACT', op: 'provenance-diff' },
  { code: 'MISSING_WIRING', op: 'gate-coverage' },
  { code: 'GATE_NOT_IN_LOCAL_SUITE', op: 'gate-coverage' },
  { code: 'UNCATALOGUED_BLOCKER', op: 'gate-coverage' },
  { code: 'UNKNOWN_TAXONOMY_OP', op: 'gate-coverage' },
  { code: 'CHAIN_BUNDLE_BLOCKED', op: 'chain-bundle' },
  { code: 'FINAL_SUMMARY_MISSING', op: 'chain-bundle' },
  { code: 'FINAL_SUMMARY_INVALID', op: 'chain-bundle' },
  { code: 'FINAL_SUMMARY_NOT_READY', op: 'chain-bundle' },
  { code: 'RELEASE_CHECKLIST_MISSING', op: 'chain-bundle' },
  { code: 'RELEASE_CHECKLIST_INVALID', op: 'chain-bundle' },
  { code: 'RELEASE_CHECKLIST_NOT_CLEARED', op: 'chain-bundle' },
  { code: 'MERGE_READINESS_MISSING', op: 'chain-bundle' },
  { code: 'MERGE_READINESS_INVALID', op: 'chain-bundle' },
  { code: 'MERGE_READINESS_NOT_READY', op: 'chain-bundle' },
  { code: 'NEGATIVE_CORPUS_MISSING', op: 'chain-bundle' },
  { code: 'NEGATIVE_CORPUS_INVALID', op: 'chain-bundle' },
  { code: 'NEGATIVE_CORPUS_BREACHED', op: 'chain-bundle' },
  { code: 'PROVENANCE_DIFF_MISSING', op: 'chain-bundle' },
  { code: 'PROVENANCE_DIFF_INVALID', op: 'chain-bundle' },
  { code: 'PROVENANCE_DIFF_MISALIGNED', op: 'chain-bundle' },
  { code: 'GATE_COVERAGE_MISSING', op: 'chain-bundle' },
  { code: 'GATE_COVERAGE_INVALID', op: 'chain-bundle' },
  { code: 'GATE_COVERAGE_INCOMPLETE', op: 'chain-bundle' },
  { code: 'COMPONENT_DIGEST_MISSING', op: 'chain-bundle' },
  { code: 'COMPONENT_DIGEST_INVALID', op: 'chain-bundle' },
  { code: 'COMPONENT_DIGEST_MISMATCH', op: 'chain-bundle' },
  { code: 'FINAL_SUMMARY_BINDING_MISMATCH', op: 'chain-bundle' },
  { code: 'LEAK_NOT_DETECTED', op: 'redaction-corpus' },
  { code: 'SAFE_VALUE_FLAGGED', op: 'redaction-corpus' },
  { code: 'FORBIDDEN_HOOK_FOUND', op: 'boundary-policy' },
  { code: 'BOUNDARY_LANGUAGE_MISSING', op: 'boundary-policy' },
  { code: 'UNSANDBOXED_PROMOTION_CALL', op: 'boundary-policy' },
  { code: 'REVIEW_AUTOMATION_BLOCKED', op: 'review-automation' },
  { code: 'CHAIN_BUNDLE_MISSING', op: 'review-automation' },
  { code: 'CHAIN_BUNDLE_INVALID', op: 'review-automation' },
  { code: 'CHAIN_BUNDLE_NOT_READY', op: 'review-automation' },
  { code: 'REDACTION_CORPUS_MISSING', op: 'review-automation' },
  { code: 'REDACTION_CORPUS_INVALID', op: 'review-automation' },
  { code: 'REDACTION_CORPUS_BREACHED', op: 'review-automation' },
  { code: 'BOUNDARY_POLICY_MISSING', op: 'review-automation' },
  { code: 'BOUNDARY_POLICY_INVALID', op: 'review-automation' },
  { code: 'BOUNDARY_POLICY_VIOLATED', op: 'review-automation' },
  { code: 'COMPONENT_DIGEST_MISSING', op: 'review-automation' },
  { code: 'COMPONENT_DIGEST_INVALID', op: 'review-automation' },
  { code: 'COMPONENT_DIGEST_MISMATCH', op: 'review-automation' },
  { code: 'REVIEWER_PACK_BLOCKED', op: 'reviewer-pack' },
  { code: 'PACK_BINDING_MISMATCH', op: 'reviewer-pack' },
  { code: 'FINAL_SUMMARY_MISSING', op: 'reviewer-pack' },
  { code: 'FINAL_SUMMARY_INVALID', op: 'reviewer-pack' },
  { code: 'FINAL_SUMMARY_NOT_READY', op: 'reviewer-pack' },
  { code: 'RELEASE_CHECKLIST_MISSING', op: 'reviewer-pack' },
  { code: 'RELEASE_CHECKLIST_INVALID', op: 'reviewer-pack' },
  { code: 'RELEASE_CHECKLIST_NOT_CLEARED', op: 'reviewer-pack' },
  { code: 'MERGE_READINESS_MISSING', op: 'reviewer-pack' },
  { code: 'MERGE_READINESS_INVALID', op: 'reviewer-pack' },
  { code: 'MERGE_READINESS_NOT_READY', op: 'reviewer-pack' },
  { code: 'CHAIN_BUNDLE_MISSING', op: 'reviewer-pack' },
  { code: 'CHAIN_BUNDLE_INVALID', op: 'reviewer-pack' },
  { code: 'CHAIN_BUNDLE_NOT_READY', op: 'reviewer-pack' },
  { code: 'REVIEW_AUTOMATION_MISSING', op: 'reviewer-pack' },
  { code: 'REVIEW_AUTOMATION_INVALID', op: 'reviewer-pack' },
  { code: 'REVIEW_AUTOMATION_NOT_PASSED', op: 'reviewer-pack' },
  { code: 'REDACTION_CORPUS_MISSING', op: 'reviewer-pack' },
  { code: 'REDACTION_CORPUS_INVALID', op: 'reviewer-pack' },
  { code: 'REDACTION_CORPUS_BREACHED', op: 'reviewer-pack' },
  { code: 'BOUNDARY_POLICY_MISSING', op: 'reviewer-pack' },
  { code: 'BOUNDARY_POLICY_INVALID', op: 'reviewer-pack' },
  { code: 'BOUNDARY_POLICY_VIOLATED', op: 'reviewer-pack' },
  { code: 'COMPONENT_DIGEST_MISSING', op: 'reviewer-pack' },
  { code: 'COMPONENT_DIGEST_INVALID', op: 'reviewer-pack' },
  { code: 'COMPONENT_DIGEST_MISMATCH', op: 'reviewer-pack' },
  { code: 'REVIEWER_PACK_MISSING', op: 'acceptance-preflight' },
  { code: 'REVIEWER_PACK_INVALID', op: 'acceptance-preflight' },
  { code: 'REVIEWER_PACK_NOT_READY', op: 'acceptance-preflight' },
  { code: 'PREFLIGHT_CONTEXT_MISSING', op: 'acceptance-preflight' },
  { code: 'PREFLIGHT_CONTEXT_INVALID', op: 'acceptance-preflight' },
  { code: 'MACHINE_GATE_FAILED', op: 'acceptance-preflight' },
  { code: 'COMPONENT_DIGEST_MISSING', op: 'acceptance-preflight' },
  { code: 'COMPONENT_DIGEST_INVALID', op: 'acceptance-preflight' },
  { code: 'REVIEWER_PACK_DIGEST_MISMATCH', op: 'acceptance-preflight' },
  { code: 'PACK_COMPONENT_INCOMPLETE', op: 'acceptance-preflight' },
  { code: 'PACK_COMPONENT_UNKNOWN', op: 'acceptance-preflight' },
  { code: 'PACK_BINDING_MISSING', op: 'acceptance-preflight' },
  { code: 'PACK_BINDING_FAILED', op: 'acceptance-preflight' },
  { code: 'PACK_BINDING_UNKNOWN', op: 'acceptance-preflight' },
  { code: 'CONTEXT_BRANCH_MISMATCH', op: 'acceptance-preflight' },
  { code: 'CONTEXT_BASE_MISMATCH', op: 'acceptance-preflight' },
  { code: 'CONTEXT_HEAD_MISMATCH', op: 'acceptance-preflight' },
  { code: 'CONTEXT_REQUIRED_TESTS_MISMATCH', op: 'acceptance-preflight' },
  { code: 'CONTEXT_COMMIT_COUNT_MISMATCH', op: 'acceptance-preflight' },
  { code: 'CONTEXT_COMMITS_MISMATCH', op: 'acceptance-preflight' },
  { code: 'HEAD_NOT_TERMINAL_COMMIT', op: 'acceptance-preflight' },
  { code: 'UNMAPPED_BLOCKER', op: 'failure-matrix' },
  { code: 'STALE_TAXONOMY', op: 'failure-matrix' },
  { code: 'MISSING_TEST_PATH', op: 'failure-matrix' },
  { code: 'BLOCKER_WITHOUT_EVIDENCE', op: 'failure-matrix' },
  { code: 'USAGE_MISSING', op: 'cli-ergonomics' },
  { code: 'HELP_MISSING', op: 'cli-ergonomics' },
  { code: 'REPORT_UNRECOGNIZED', op: 'report-schema' },
  { code: 'REPORT_SHAPE_INVALID', op: 'report-schema' },
  { code: 'UNKNOWN_KEY', op: 'report-schema' },
  { code: 'REPORT_STATUS_INVALID', op: 'report-schema' },
  { code: 'REPORT_DIGEST_INVALID', op: 'report-schema' },
  { code: 'REPORT_DIGEST_MISMATCH', op: 'report-schema' },
  { code: 'AUDIT_POLICY_VIOLATED', op: 'boundary-audit' },
  { code: 'AUDIT_NETWORK_URL_FOUND', op: 'boundary-audit' },
  { code: 'AUDIT_ENV_READ_FOUND', op: 'boundary-audit' },
  { code: 'AUDIT_NON_LOCAL_SUITE', op: 'boundary-audit' },
  { code: 'AUDIT_DOC_DRIFT', op: 'boundary-audit' },
  { code: 'ACCEPTANCE_PREFLIGHT_MISSING', op: 'coordinator-readiness' },
  { code: 'ACCEPTANCE_PREFLIGHT_INVALID', op: 'coordinator-readiness' },
  { code: 'ACCEPTANCE_PREFLIGHT_NOT_READY', op: 'coordinator-readiness' },
  { code: 'FAILURE_MATRIX_MISSING', op: 'coordinator-readiness' },
  { code: 'FAILURE_MATRIX_INVALID', op: 'coordinator-readiness' },
  { code: 'FAILURE_MATRIX_INCOMPLETE', op: 'coordinator-readiness' },
  { code: 'REPORT_SCHEMA_MISSING', op: 'coordinator-readiness' },
  { code: 'REPORT_SCHEMA_INVALID', op: 'coordinator-readiness' },
  { code: 'REPORT_SCHEMA_NOT_OK', op: 'coordinator-readiness' },
  { code: 'BOUNDARY_AUDIT_MISSING', op: 'coordinator-readiness' },
  { code: 'BOUNDARY_AUDIT_INVALID', op: 'coordinator-readiness' },
  { code: 'BOUNDARY_AUDIT_FAILED', op: 'coordinator-readiness' },
  { code: 'CLI_ERGONOMICS_MISSING', op: 'coordinator-readiness' },
  { code: 'CLI_ERGONOMICS_INVALID', op: 'coordinator-readiness' },
  { code: 'CLI_ERGONOMICS_NOT_OK', op: 'coordinator-readiness' },
  { code: 'COMPONENT_DIGEST_MISSING', op: 'coordinator-readiness' },
  { code: 'COMPONENT_DIGEST_INVALID', op: 'coordinator-readiness' },
  { code: 'COMPONENT_DIGEST_MISMATCH', op: 'coordinator-readiness' },
  { code: 'TRANSCRIPT_MISSING', op: 'transcript-verifier' },
  { code: 'TRANSCRIPT_INVALID', op: 'transcript-verifier' },
  { code: 'TRANSCRIPT_NOT_CLEAN', op: 'transcript-verifier' },
  { code: 'EXPECTED_COMMANDS_MISSING', op: 'transcript-verifier' },
  { code: 'HEAD_MISMATCH', op: 'transcript-verifier' },
  { code: 'COMMAND_MISSING', op: 'transcript-verifier' },
  { code: 'TEST_EXIT_NONZERO', op: 'transcript-verifier' },
  { code: 'MINIMIZED_LEAK', op: 'evidence-minimizer' },
  { code: 'BASE_MISSING', op: 'commit-range-closure' },
  { code: 'HEAD_MISSING', op: 'commit-range-closure' },
  { code: 'NO_COMMITS', op: 'commit-range-closure' },
  { code: 'COMMIT_SHA_MALFORMED', op: 'commit-range-closure' },
  { code: 'COMMIT_SUBJECT_LEAK', op: 'commit-range-closure' },
  { code: 'COMMIT_UNCATEGORIZED', op: 'commit-range-closure' },
  { code: 'BLOCKER_UNCATALOGUED', op: 'regression-oracle' },
  { code: 'REPRO_MISSING_TEST', op: 'regression-oracle' },
  { code: 'FINDING_WITHOUT_REPRO', op: 'regression-oracle' },
  { code: 'TRANSCRIPT_VERIFICATION_MISSING', op: 'terminal-closure' },
  { code: 'TRANSCRIPT_VERIFICATION_INVALID', op: 'terminal-closure' },
  { code: 'TRANSCRIPT_VERIFICATION_NOT_VERIFIED', op: 'terminal-closure' },
  { code: 'EVIDENCE_MINIMIZER_MISSING', op: 'terminal-closure' },
  { code: 'EVIDENCE_MINIMIZER_INVALID', op: 'terminal-closure' },
  { code: 'EVIDENCE_MINIMIZER_NOT_CLEAN', op: 'terminal-closure' },
  { code: 'COMMIT_RANGE_CLOSURE_MISSING', op: 'terminal-closure' },
  { code: 'COMMIT_RANGE_CLOSURE_INVALID', op: 'terminal-closure' },
  { code: 'COMMIT_RANGE_NOT_CLOSED', op: 'terminal-closure' },
  { code: 'REGRESSION_ORACLE_MISSING', op: 'terminal-closure' },
  { code: 'REGRESSION_ORACLE_INVALID', op: 'terminal-closure' },
  { code: 'REGRESSION_ORACLE_INCOMPLETE', op: 'terminal-closure' },
  { code: 'COORDINATOR_READINESS_MISSING', op: 'terminal-closure' },
  { code: 'COORDINATOR_READINESS_INVALID', op: 'terminal-closure' },
  { code: 'COORDINATOR_READINESS_NOT_CONFIRMED', op: 'terminal-closure' },
  { code: 'COMPONENT_DIGEST_MISSING', op: 'terminal-closure' },
  { code: 'COMPONENT_DIGEST_INVALID', op: 'terminal-closure' },
  { code: 'COMPONENT_DIGEST_MISMATCH', op: 'terminal-closure' },
  { code: 'PACK_MISSING', op: 'pack-component-integrity' },
  { code: 'PACK_INVALID', op: 'pack-component-integrity' },
  { code: 'PACK_DIGEST_MISMATCH', op: 'pack-component-integrity' },
  { code: 'PACK_NOT_READY', op: 'pack-component-integrity' },
  { code: 'COMPONENT_REPORT_MISSING', op: 'pack-component-integrity' },
  { code: 'COMPONENT_REPORT_INVALID', op: 'pack-component-integrity' },
  { code: 'COMPONENT_DIGEST_MISMATCH', op: 'pack-component-integrity' },
  { code: 'COMPONENT_NOT_GREEN', op: 'pack-component-integrity' },
  { code: 'PACK_DIGEST_UNBOUND', op: 'pack-component-integrity' },
  { code: 'PACK_COMPONENT_DIGEST_MISMATCH', op: 'pack-component-integrity' },
  { code: 'RECOMPUTE_ABSENT', op: 'aggregator-digest-audit' },
  { code: 'MISMATCH_NOT_ENFORCED', op: 'aggregator-digest-audit' },
  { code: 'MISMATCH_UNTESTED', op: 'aggregator-digest-audit' },
  { code: 'NO_BINDERS_FOUND', op: 'aggregator-digest-audit' },
  { code: 'ARTIFACT_REPORT_UNREGISTERED', op: 'artifact-export-manifest' },
  { code: 'ARTIFACT_NOT_GENERATABLE', op: 'artifact-export-manifest' },
  { code: 'ARTIFACT_EXPORT_UNSUPPORTED', op: 'artifact-export-manifest' },
  { code: 'ARTIFACT_CLI_NONCONFORMANT', op: 'artifact-export-manifest' },
  { code: 'NO_ARTIFACTS_FOUND', op: 'artifact-export-manifest' },
  { code: 'WATCHER_CONFIG_MISSING', op: 'watchdog-hygiene' },
  { code: 'WATCHER_DEBOUNCE_MISSING', op: 'watchdog-hygiene' },
  { code: 'WATCHER_NOT_IDEMPOTENT', op: 'watchdog-hygiene' },
  { code: 'WATCHER_AUTO_PROMOTE_ENABLED', op: 'watchdog-hygiene' },
  { code: 'WATCHER_LIVE_BOUNDARY_UNGUARDED', op: 'watchdog-hygiene' },
  { code: 'WATCHER_DEDUPE_DISABLED', op: 'watchdog-hygiene' },
  { code: 'WATCHER_CONFIG_UNKNOWN_FIELD', op: 'watchdog-hygiene' },
  { code: 'QUEUE_MISSING', op: 'watchdog-hygiene' },
  { code: 'ENTRY_DIGEST_MALFORMED', op: 'watchdog-hygiene' },
  { code: 'ENTRY_STATUS_INVALID', op: 'watchdog-hygiene' },
  { code: 'ENTRY_RUN_MISSING', op: 'watchdog-hygiene' },
  { code: 'DUPLICATE_QUEUE_ENTRY', op: 'watchdog-hygiene' },
  { code: 'STALE_QUEUE_ENTRY', op: 'watchdog-hygiene' },
  { code: 'TERMINAL_CLOSURE_MISSING', op: 'terminal-readiness-v2' },
  { code: 'TERMINAL_CLOSURE_INVALID', op: 'terminal-readiness-v2' },
  { code: 'TERMINAL_CLOSURE_NOT_CONFIRMED', op: 'terminal-readiness-v2' },
  { code: 'PACK_INTEGRITY_MISSING', op: 'terminal-readiness-v2' },
  { code: 'PACK_INTEGRITY_INVALID', op: 'terminal-readiness-v2' },
  { code: 'PACK_INTEGRITY_NOT_VERIFIED', op: 'terminal-readiness-v2' },
  { code: 'AGGREGATOR_AUDIT_MISSING', op: 'terminal-readiness-v2' },
  { code: 'AGGREGATOR_AUDIT_INVALID', op: 'terminal-readiness-v2' },
  { code: 'AGGREGATOR_AUDIT_NOT_CLEAN', op: 'terminal-readiness-v2' },
  { code: 'ARTIFACT_EXPORT_MISSING', op: 'terminal-readiness-v2' },
  { code: 'ARTIFACT_EXPORT_INVALID', op: 'terminal-readiness-v2' },
  { code: 'ARTIFACT_EXPORT_NOT_COMPLETE', op: 'terminal-readiness-v2' },
  { code: 'NEGATIVE_CORPUS_MISSING', op: 'terminal-readiness-v2' },
  { code: 'NEGATIVE_CORPUS_INVALID', op: 'terminal-readiness-v2' },
  { code: 'NEGATIVE_CORPUS_BREACHED', op: 'terminal-readiness-v2' },
  { code: 'WATCHDOG_HYGIENE_MISSING', op: 'terminal-readiness-v2' },
  { code: 'WATCHDOG_HYGIENE_INVALID', op: 'terminal-readiness-v2' },
  { code: 'WATCHDOG_HYGIENE_VIOLATED', op: 'terminal-readiness-v2' },
  { code: 'COMPONENT_DIGEST_MISSING', op: 'terminal-readiness-v2' },
  { code: 'COMPONENT_DIGEST_INVALID', op: 'terminal-readiness-v2' },
  { code: 'COMPONENT_DIGEST_MISMATCH', op: 'terminal-readiness-v2' },
  { code: 'BASE_MISSING', op: 'review-matrix' },
  { code: 'HEAD_MISSING', op: 'review-matrix' },
  { code: 'NO_COMMITS', op: 'review-matrix' },
  { code: 'COMMIT_SHA_MALFORMED', op: 'review-matrix' },
  { code: 'COMMIT_SUBJECT_LEAK', op: 'review-matrix' },
  { code: 'HEAD_NOT_TERMINAL_COMMIT', op: 'review-matrix' },
  { code: 'NO_TESTS', op: 'review-matrix' },
  { code: 'TEST_NAME_LEAK', op: 'review-matrix' },
  { code: 'READINESS_MISSING', op: 'review-authorization' },
  { code: 'READINESS_INVALID', op: 'review-authorization' },
  { code: 'READINESS_NOT_CONFIRMED', op: 'review-authorization' },
  { code: 'REVIEW_MATRIX_MISSING', op: 'review-authorization' },
  { code: 'REVIEW_MATRIX_INVALID', op: 'review-authorization' },
  { code: 'REVIEW_MATRIX_NOT_READY', op: 'review-authorization' },
  { code: 'TERMINAL_CLOSURE_MISSING', op: 'review-authorization' },
  { code: 'TERMINAL_CLOSURE_INVALID', op: 'review-authorization' },
  { code: 'TERMINAL_CLOSURE_NOT_CONFIRMED', op: 'review-authorization' },
  { code: 'TERMINAL_CLOSURE_NOT_BOUND', op: 'review-authorization' },
  { code: 'COMMIT_RANGE_CLOSURE_MISSING', op: 'review-authorization' },
  { code: 'COMMIT_RANGE_CLOSURE_INVALID', op: 'review-authorization' },
  { code: 'COMMIT_RANGE_NOT_CLOSED', op: 'review-authorization' },
  { code: 'COMMIT_RANGE_NOT_BOUND', op: 'review-authorization' },
  { code: 'TRANSCRIPT_VERIFICATION_MISSING', op: 'review-authorization' },
  { code: 'TRANSCRIPT_VERIFICATION_INVALID', op: 'review-authorization' },
  { code: 'TRANSCRIPT_VERIFICATION_NOT_VERIFIED', op: 'review-authorization' },
  { code: 'TRANSCRIPT_VERIFICATION_NOT_BOUND', op: 'review-authorization' },
  { code: 'CONTEXT_BASE_MISMATCH', op: 'review-authorization' },
  { code: 'CONTEXT_HEAD_MISMATCH', op: 'review-authorization' },
  { code: 'CONTEXT_COMMITS_MISMATCH', op: 'review-authorization' },
  { code: 'CONTEXT_REQUIRED_TESTS_MISMATCH', op: 'review-authorization' },
  { code: 'CONTEXT_TRANSCRIPT_HEAD_MISMATCH', op: 'review-authorization' },
  { code: 'COMPONENT_DIGEST_MISSING', op: 'review-authorization' },
  { code: 'COMPONENT_DIGEST_INVALID', op: 'review-authorization' },
  { code: 'COMPONENT_DIGEST_MISMATCH', op: 'review-authorization' },
  { code: 'COMPONENT_UNVERIFIED', op: 'context-consistency-audit' },
  { code: 'INSUFFICIENT_CONTEXT_COMPONENTS', op: 'context-consistency-audit' },
  { code: 'CONTEXT_BRANCH_INCONSISTENT', op: 'context-consistency-audit' },
  { code: 'CONTEXT_BASE_INCONSISTENT', op: 'context-consistency-audit' },
  { code: 'CONTEXT_HEAD_INCONSISTENT', op: 'context-consistency-audit' },
  { code: 'CONTEXT_COMMITS_INCONSISTENT', op: 'context-consistency-audit' },
  { code: 'CONTEXT_TESTS_INCONSISTENT', op: 'context-consistency-audit' },
  { code: 'CONTEXT_HEAD_NOT_TERMINAL', op: 'context-consistency-audit' },
  { code: 'UNBOUND_TERMINAL_CONTEXT', op: 'closure-summary-v3' },
  { code: 'UNBOUND_COORDINATOR_CONTEXT', op: 'closure-summary-v3' },
  { code: 'OBSERVED_STATE_MISSING', op: 'closure-summary-v3' },
  { code: 'OBSERVED_STATE_UNBOUND', op: 'closure-summary-v3' },
  { code: 'COMPONENT_DIGEST_UNVERIFIED', op: 'closure-summary-v3' },
  { code: 'LIVE_BOUNDARY_ESCAPE', op: 'closure-summary-v3' },
  { code: 'BUNDLE_ROOT_UNRESOLVED', op: 'closure-input-bundle-audit' },
  { code: 'DUPLICATE_REPORT_ID', op: 'closure-input-bundle-audit' },
  { code: 'NO_REPORTS', op: 'closure-input-bundle-audit' },
];

export interface CategorizedBlocker { readonly code: string; readonly op: string; readonly category: string; }

export interface BlockerTaxonomyReport {
  readonly report: 'phase-230-promotion-blocker-taxonomy';
  readonly version: 1;
  readonly redactionSafe: true;
  readonly authorization: 'NONE';
  readonly overall: 'TAXONOMY_CONSISTENT' | 'TAXONOMY_INCONSISTENT';
  readonly count: number;
  readonly categories: Readonly<Record<string, number>>;
  readonly entries: readonly CategorizedBlocker[];
  readonly problems: readonly string[];
  readonly taxonomyDigest: string;
}

export function categoryOf(code: string): string {
  if (/_MISSING$/.test(code)) return 'missing';
  if (/_INVALID$/.test(code)) return 'invalid';
  if (/MISMATCH/.test(code)) return 'mismatch';
  if (/INCOMPLETE|INSUFFICIENT/.test(code)) return 'incomplete';
  if (/LEAK/.test(code)) return 'leak';
  if (/NOT_|_FAIL$|FORBIDDEN|REQUIRED|REJECTED|BLOCKED|DETECTED|NON_DETERMINISTIC|VIOLATION|CYCLE|UNKNOWN|UNRECOGNIZED/.test(code)) return 'not-ready';
  return 'other';
}

// Every distinct blocker code the local tooling can emit (sorted), for cross-checks by other gates.
export const BLOCKER_CODES: readonly string[] = [...new Set(BLOCKERS.map((b) => b.code))].sort();

export function buildBlockerTaxonomy(): BlockerTaxonomyReport {
  const problems: string[] = [];
  const seen = new Set<string>();
  const entries: CategorizedBlocker[] = BLOCKERS.map((b) => {
    if (!/^[A-Z][A-Z0-9_]*$/.test(b.code)) problems.push('MALFORMED_CODE');
    if (b.op.length === 0) problems.push('MISSING_OP');
    const key = `${b.code} ${b.op}`;
    if (seen.has(key)) problems.push('DUPLICATE_ENTRY'); else seen.add(key);
    return { code: b.code, op: b.op, category: categoryOf(b.code) };
  });

  const categories: Record<string, number> = {};
  for (const code of BLOCKER_CODES) { const c = categoryOf(code); categories[c] = (categories[c] ?? 0) + 1; }

  const overall: BlockerTaxonomyReport['overall'] = problems.length === 0 ? 'TAXONOMY_CONSISTENT' : 'TAXONOMY_INCONSISTENT';
  const withoutDigest: Omit<BlockerTaxonomyReport, 'taxonomyDigest'> = {
    report: 'phase-230-promotion-blocker-taxonomy',
    version: 1,
    redactionSafe: true,
    authorization: 'NONE',
    overall,
    count: BLOCKER_CODES.length,
    categories,
    entries,
    problems: [...new Set(problems)],
  };
  return { ...withoutDigest, taxonomyDigest: digest('phase-230-blocker-taxonomy', JSON.stringify(withoutDigest)) };
}

function digest(scope: string, value: string): string {
  return createHash('sha256').update(`${scope}:${value}`).digest('hex');
}
